INSERT INTO tests(id, name) VALUES (1, "japanese vocabulary");

INSERT INTO test (original, phonetic, translation, testid) VALUES
("の", "no", "of; in; at; for; by", 1),
("に", "ni", "at; on; in; to; for", 1),
("は", "wa", "p. TOPIC", 1),
("た", "ta", "aux. PAST", 1),
("を", "o", "p. case ACCUSATIVE", 1),
("だ", "da", "aux. COPULA", 1),
("が", "ga", "p. case NOMINATIVE", 1),
("て", "te", "p. conj. REASON", 1),
("と", "to", "and; or; with; if", 1),
("ます", "masu", "aux. POLITE (after verb)", 1),
("も", "mo", "too, also", 1),
("で", "de", "case in; at; from; by", 1),
("ている", "te iru", "cp. CONTINUATION", 1),
("てる", "teru", "cp. CONTINUATION", 1),
("です", "desu", "aux. COPULA (polite)", 1),
("れる", "reru", "aux. PASSIVE", 1),
("という", "to yuu", "cp. called", 1),
("つう", "to tsu", "cp. called", 1),
("事", "koto", "thing", 1),
("えー", "ee", "eh?", 1),
("ええ", "ee", "eh?", 1),
("言う", "yuu", "v. say, speak, talk", 1),
("のです", "no desu", "ASSERTION (polite)", 1),
("んです", "n desu", "ASSERTION (polite)", 1),
("あの", "ano", "ano", 1),
("する", "suru", "v. do; make", 1),
("まー", "maa", "interj. Wow!, Oh my God!", 1),
("まあ", "maa", "interj. Wow!, Oh my God!", 1),
("の", "no", "p. POSSESSIVE", 1),
("ある", "aru", "v. be (existence), have (possession), happen, occur", 1),
("ね", "ne", "p. disc. isn’t it?, don’t you?", 1),
("ない", "nai", "aux. not", 1),
("なる", "naru", "v. become, get; come to do, start to do; turn into", 1),
("か", "ka", "p. disc. QUESTION", 1),
("その", "sono", "adn. that", 1),
("けれど", "keredo", "though, although", 1),
("から", "kara", "p. case from", 1),
("よう", "you", "aux. INDUCEMENT", 1),
("思う", "omou", "v. think, believe; feel; expect", 1),
("で", "de", "so, then", 1),
("か", "ka", "if; or", 1),
("が", "ga", "p. conj. ADVERSATIVE", 1),
("物", "mono", "thing, object, stuff", 1),
("そう", "sou", "so, such", 1),
("何", "nani", "what; something; anything; nothing", 1),
("私", "watashi, watakushi, atashi", "I", 1),
("てしまう", "te", "shimau cp. end up doing ...", 1),
("それ", "sore", "that", 1),
("と", "to", "if, when; with", 1),
("とか", "to ka", "and; or", 1),
("この", "kono", "adn. this", 1),
("無い", "nai", "i-adj. There is no ..., no ...", 1),
("行く", "iku, yuku", "v. go; come", 1),
("んだ", "no da", "cp. ASSERTION", 1),
("んだ", "n da", "cp. ASSERTION", 1),
("せる", "seru", "aux. CAUSATIVE", 1),
("これ", "kore", "pron. this", 1),
("もう", "moo", "adv. already; soon; again", 1),
("である", "de aru", "cp. COPULA (formal)", 1),
("時", "toki", "n. time", 1),
("な", "na", "p. disc. PROHIBITION", 1),
("ず", "zu", "aux. NEGATION", 1),
("ので", "no de", "p. conj. as, because, since", 1),
("んで", "n de", "p. conj. as, because, since", 1),
("人", "hito", "n. person, people, human being", 1),
("よ", "yo", "p. disc. ASSERTION, REMINDING (informal)", 1),
("こう", "koo", "adv. so, like this", 1),
("から", "kara", "p. conj. because, since", 1),
("ば", "ba", "p. conj. if", 1),
("や", "ya", "p. and; or", 1),
("来る", "kuru", "v. come", 1),
("その", "sono", "interj. uh, er, um, mm", 1),
("まで", "made", "p. to, till, until", 1),
("見る", "miru", "v. see; look at, watch; check", 1),
("たり", "tari", "p. and", 1),
("今", "ima", "n. now", 1),
("良い", "yoi", "i-adj. good", 1),
("いい", "ii", "i-adj. good", 1),
("所", "tokoro", "n. place, point; part; aspect", 1),
("自分", "jibun", "n. oneself", 1),
("ん", "n", "interj. oh, mm, well", 1),
("あー", "aa", "interj. er, uh, um, hmm, ah, oh", 1),
("やっぱり", "yappari", "adv. as (one) expected, still", 1),
("やはり", "yahari", "adv. as (one) expected, still", 1),
("たい", "tai", "aux. want to, like to", 1),
("やる", "yaru", "v. do; make; give", 1),
("中", "naka", "n. inside, in; into", 1),
("いる", "iru", "v. be, exist; stay", 1),
("できる", "dekiru", "v. be ready", 1),
("など", "nado", "p. and so on, etc.", 1),
("として", "to shi te", "cp. as", 1),
("後", "ato", "n. after, later", 1),
("また", "mata", "adv. additionally, moreover conj. again; too, and", 1),
("ちょっと", "chotto", "adv. (just) a little, a bit", 1),
("てくる", "te kuru", "cp. go and ...", 1),
("だけ", "dake", "p. only, alone, merely", 1),
("ぐらい", "gurai", "p. about, around", 1),
("くらい", "kurai", "p. about, around", 1),
("ではない", "de wa nai", "cp. it is not the case that  ...", 1),
("えーと", "eeto", "interj. well, let me see", 1),
("方", "hou", "n. direction, way; side", 1),
("ていく", "te iku", "cp. go and  ...", 1),
("てく", "teku", "cp. go and  ...", 1),
("訳", "wake", "n. reason, cause", 1),
("へ", "e", "p. case DESTINATION", 1),
("どう", "dou", "adv. how, what", 1),
("し", "shi", "p. conj. and, besides", 1),
("本当", "hontou", "n. truth, right", 1),
("ため", "tame", "n. for", 1),
("すごい", "sugoi", "i-adj. fantastic, wonderful; terrible", 1),
("考える", "kangaeru", "v. think", 1),
("そこ", "soko", "pron. there; then", 1),
("う", "u", "aux. SOLICITATION", 1),
("分かる", "wakaru", "v. understand, see", 1),
("ておる", "te oru", "cp. CONTINUATION (polite)", 1),
("について", "ni tsui te", "cp. about, concerning, as to", 1),
("それで", "sore de", "conj. and then; so; that is why", 1),
("入る", "hairu", "v. enter, come in, go in", 1),
("作る", "tsukuru", "v. make, create, cook", 1),
("てみる", "te miru", "cp. try  ...ing", 1),
("聞く", "kiku", "v. hear; listen; listen to, obey", 1),
("聴く", "kiku", "v. hear; listen; listen to, obey", 1),
("そして", "soshite", "conj. and, so", 1),
("てくれる", "te kureru", "cp. [do something as a favor]", 1),
("持つ", "motsu", "v. have, take, hold", 1),
("出る", "deru", "v. go out, come out; attend", 1)
;
