INSERT INTO tests(id, name) VALUES (3, "russian vocabulary");

INSERT INTO test (original, translation, testid) VALUES
("и", "and, though", 3),
("в", "in, at", 3),
("не", "not", 3),
("он", "he", 3),
("на", "on, it, at, to", 3),
("я", "I", 3),
("что", "what, that, why", 3),
("тот", "that", 3),
("быть", "to be", 3),
("с", "with, and, from, of", 3),
("а", "while, and, but", 3),
("весь", "all, everything", 3),
("это", "that, this, it", 3),
("как", "how, what, as, like", 3),
("она", "she", 3),
("по", "on, along, by", 3),
("но", "but", 3),
("они", "they", 3),
("к", "to, for, by", 3),
("у", "by, with, of", 3),
("ты", "you, thou", 3),
("из", "from, of, in", 3),
("мы", "we", 3),
("за", "behind, over, at, after", 3),
("вы", "you", 3),
("так", "so, thus, then", 3),
("же", "and, as for, but, same", 3),
("от", "from, of, for", 3),
("сказать", "to say, to speak", 3),
("этот", "this", 3),
("который", "which, who, that", 3),
("мочь", "be able", 3),
("человек", "man, person", 3),
("о", "of, about, against", 3),
("один", "one, some, alone", 3),
("ещё", "still, yet", 3),
("бы", "would", 3),
("такой", "such, so, some", 3),
("только", "only, merely, but", 3),
("себя", "myself, himself, herself", 3),
("своё", "one's own, my, our", 3),
("какой", "what, which, how", 3),
("когда", "when, while, as", 3),
("уже", "already, by now", 3),
("для", "for, to", 3),
("вот", "here, there, this is, that's", 3),
("кто", "who, that, some", 3),
("да", "yes, but", 3),
("говорить", "to say, to tell, to speak", 3),
("год", "year", 3),
("знать", "to know, be aware", 3),
("мой", "my, mine", 3),
("до", "to, up to, about, before", 3),
("или", "or", 3),
("если", "if", 3),
("время", "time, season", 3),
("рука", "hand, arm", 3),
("нет", "no, not, but", 3),
("самый", "most, the very, the same", 3),
("ни", "not a, not, neither… nor", 3),
("стать", "to become, begin, come", 3),
("большой", "big, large, important", 3),
("даже", "even", 3),
("другой", "other, another, different", 3),
("наш", "our, ours", 3),
("свой", "my, our, your", 3),
("ну", "now, right, well, come on", 3),
("под", "under, for, towards, to", 3),
("где", "where", 3),
("дело", "business, affair, matter", 3),
("есть", "to eat, to be", 3),
("сам", "myself, yourself", 3),
("раз", "time, once, since", 3),
("чтобы", "that, in order that", 3),
("два", "two", 3),
("там", "there, then", 3),
("чем", "than; instead of", 3),
("глаз", "eye; sight", 3),
("жизнь", "life", 3),
("первый", "first, front, former", 3),
("день", "day", 3),
("тут", "here, now, then", 3),
("во", "in, at; super, exactly", 3),
("ничто", "nothing", 3),
("потом", "afterwards, then", 3),
("очень", "very", 3),
("со", "with", 3),
("хотеть", "to want, like", 3),
("ли", "whether, if", 3),
("при", "attached to, in the presence of, by, about; masterrussian, dot com", 3),
("голова", "head, mind, brains", 3),
("надо", "over, above, ought to", 3),
("без", "without", 3),
("видеть", "to see", 3),
("идти", "to go, come", 3),
("теперь", "now, nowadays", 3),
("тоже", "also, as well, too", 3),
("стоять", "to stand, be, stand up", 3),
("друг", "friend", 3),
("дом", "house, home", 3),
("сейчас", "now, presently, soon", 3),
("можно", "one can", 3),
("после", "after, afterwards", 3),
("слово", "word", 3),
("здесь", "here", 3),
("думать", "to think; believe", 3),
("место", "place; seat", 3),
("спросить", "to ask", 3),
("через", "through, across", 3),
("лицо", "face; person", 3),
("что", "what, which, that", 3),
("тогда", "then", 3),
("ведь", "you see, you know", 3),
("хороший", "good, nice (see #152, 3)", 3),
("каждый", "each, every", 3),
("новый", "new; modern", 3),
("жить", "to live", 3),
("должный", "due, proper", 3),
("смотреть", "to look, watch", 3),
("почему", "why", 3),
("потому", "that's why", 3),
("сторона", "side, party", 3),
("просто", "simply", 3),
("нога", "foot, leg", 3),
("сидеть", "to sit", 3),
("понять", "to understand; realize", 3),
("иметь", "to have, own", 3),
("конечный", "final, last", 3),
("делать", "to do, make", 3),
("вдруг", "suddenly", 3),
("над", "above, over", 3),
("взять", "to take", 3),
("никто", "nobody", 3),
("сделать", "to do, make, finish", 3),
("дверь", "door", 3),
("перед", "before, in front of", 3),
("нужный", "necessary", 3),
("понимать", "to understand", 3),
("казаться", "to seem, appear; masterrussian, dot com", 3),
("работа", "work, job", 3),
("три", "three", 3),
("ваш", "yours", 3),
("уж", "really, already", 3),
("земля", "earth, land, soil", 3),
("конец", "end, distance", 3),
("несколько", "several, some", 3),
("час", "hour, time", 3),
("голос", "voice", 3),
("город", "town, city", 3),
("последний", "last, the latest, new", 3),
("пока", "for the present", 3),
("хорошо", "well (see #114, 3)", 3),
("давать", "to give; let, allow", 3),
("вода", "water", 3),
("более", "more", 3),
("хотя", "although", 3),
("всегда", "always", 3),
("второй", "second", 3),
("куда", "where, what for, much", 3),
("пойти", "to go", 3),
("стол", "table, desk; board", 3),
("ребёнок", "child, kid, infant", 3),
("увидеть", "to see", 3),
("сила", "strength, force", 3),
("отец", "father (see #918, 3)", 3),
("женщина", "woman", 3),
("машина", "car, machine, engine", 3),
("случай", "case, occasion, incident", 3),
("ночь", "night", 3),
("сразу", "at once, right away, just", 3),
("мир", "world, peace", 3),
("совсем", "quite, entirely, totally", 3),
("остаться", "to remain, stay (see #297, 3)", 3),
("об", "about, of (see #34, 3)", 3),
("вид", "appearance, look, view", 3),
("выйти", "to go out, come out, appear", 3),
("дать", "to give; masterrussian, dot com", 3),
("работать", "to work", 3),
("любить", "to love", 3),
("старый", "old", 3),
("почти", "almost", 3),
("ряд", "row, line", 3),
("оказаться", "find oneself, turn out", 3),
("начало", "beginning, origin, source", 3),
("твой", "your, yours (informal, 3)", 3),
("вопрос", "question, matter, problem", 3),
("много", "many, much (see #799, 3)", 3),
("война", "war", 3),
("снова", "again", 3),
("ответить", "to answer, reply (see #404, 3)", 3),
("между", "between, among", 3),
("подумать", "to think", 3),
("опять", "again", 3),
("белый", "white", 3),
("деньги", "money", 3),
("значить", "to mean, signify", 3),
("про", "about, for", 3),
("лишь", "only, as soon as", 3),
("минута", "minute, moment", 3),
("жена", "wife", 3),
("посмотреть", "to take a look, watch, inspect", 3),
("правда", "truth", 3),
("главный", "main, chief", 3),
("страна", "country", 3),
("свет", "light;world", 3),
("ждать", "to wait", 3),
("мать", "mother", 3),
("будто", "as if, as though", 3),
("никогда", "never", 3),
("товарищ", "comrade, friend", 3),
("дорога", "road, way, journey", 3),
("однако", "however, though", 3),
("лежать", "to lie, be situated", 3),
("именно", "namely, just", 3),
("окно", "window, windowsill", 3),
("никакой", "no, none", 3),
("найти", "to find, discover, consider", 3),
("писать", "to write", 3),
("комната", "a room", 3),
("Москва", "Moscow", 3),
("часть", "part, share, department", 3),
("вообще", "in general, altogether, on the whole", 3),
("книга", "a book", 3),
("маленький", "small, little", 3),
("улица", "street; masterrussian, dot com", 3),
("решить", "to decide, solve", 3),
("далекий", "distant, remote", 3),
("душа", "soul, spirit", 3),
("чуть", "hardly, slightly", 3),
("вернуться", "to return", 3),
("утро", "morning", 3),
("некоторый", "some", 3),
("считать", "to count, consider", 3),
("сколько", "how much, how many", 3),
("помнить", "to remember", 3),
("вечер", "evening", 3),
("пол", "floor; sex", 3),
("таки", "after all", 3),
("получить", "to receive, get, obtain", 3),
("народ", "people, nation", 3),
("плечо", "shoulder, upper arm", 3),
("хоть", "even, if you want, though", 3),
("сегодня", "today", 3),
("бог", "god", 3),
("вместе", "together", 3),
("взгляд", "look, glance; view", 3),
("ходить", "to go, walk", 3),
("зачем", "what for, why", 3),
("советский", "Soviet", 3),
("русский", "Russian", 3),
("бывать", "be, visit, happen", 3),
("полный", "full, complete", 3),
("прийти", "to come, arrive (see #464, 3)", 3),
("палец", "finger, toe", 3),
("Россия", "Russia", 3),
("любой", "any, every", 3),
("история", "history, story, event", 3),
("наконец", "at last, finally", 3),
("мысль", "thought, idea", 3),
("узнать", "to know, learn, recognize", 3),
("назад", "back, backwards", 3),
("общий", "general, common", 3),
("заметить", "to notice, observe", 3),
("словно", "as if, like", 3),
("прошлый", "past", 3),
("уйти", "to leave, go away", 3),
("известный", "well-known, famous", 3),
("давно", "long ago", 3),
("слышать", "to hear", 3),
("слушать", "to listen, hear", 3),
("бояться", "to be afraid, fear", 3),
("сын", "son", 3),
("нельзя", "it is impossible, can't", 3),
("прямо", "straight, frankly", 3),
("долго", "for a long time", 3),
("быстро", "fast, quickly", 3),
("лес", "forest", 3),
("похожий", "similar, alike", 3),
("пора", "time; pore (see #1000, 3)", 3),
("пять", "five", 3),
("глядеть", "to look, gaze", 3),
("оно", "it", 3),
("сесть", "to sit", 3),
("имя", "name", 3),
("ж", "and, as for, but (see #27, 3)", 3),
("разговор", "talk, conversation", 3),
("тело", "body", 3),
("молодой", "young (see #679, 3); bridegroom (as a noun, 3)", 3),
("стена", "wall", 3),
("красный", "red", 3),
("читать", "to read", 3),
("право", "right", 3),
("старик", "old man", 3),
("ранний", "early", 3),
("хотеться", "want, like", 3),
("мама", "mummy, mum", 3),
("оставаться", "to remain, stay (see #173, 3)", 3),
("высокий", "tall, high", 3),
("путь", "way, track, path", 3),
("поэтому", "therefore", 3),
("совершенно", "absolutely, quite", 3),
("кроме", "except, besides", 3),
("тысяча", "a thousand", 3),
("месяц", "month", 3),
("брать", "to take; hire", 3),
("написать", "to write", 3),
("целый", "intact, whole, entire", 3),
("огромный", "huge, enormous", 3),
("начинать", "to begin (see #413, 3)", 3),
("спина", "back", 3),
("настоящий", "present;real, true", 3),
("пусть", "let's, though", 3),
("язык", "tongue, language", 3),
("точно", "exactly", 3),
("среди", "among", 3),
("чувствовать", "to feel", 3),
("сердце", "heart", 3),
("вести", "to lead", 3),
("иногда", "sometimes", 3),
("мальчик", "boy", 3),
("успеть", "to be in time, be successful", 3),
("небо", "sky", 3),
("живой", "living, live, lively", 3),
("смерть", "death", 3),
("продолжать", "to continue", 3),
("девушка", "girl, miss (see #524, 3)", 3),
("образ", "shape, form, image", 3),
("ко", "to, towards, by (see #19, 3)", 3),
("забыть", "to forget", 3),
("вокруг", "around", 3),
("письмо", "letter", 3),
("власть", "power", 3),
("чёрный", "black (see #456, 3)", 3),
("пройти", "to pass, go by, be over (see #543, 3)", 3),
("появиться", "to appear, show up (see #699, 3)", 3),
("воздух", "air", 3),
("разный", "different", 3),
("выходить", "to go out; nurse (see #176, 3)", 3),
("просить", "to ask", 3),
("брат", "brother", 3),
("собственный", "one's own; masterrussian, dot com", 3),
("отношение", "relationship, attitude", 3),
("затем", "then, after that", 3),
("пытаться", "to try", 3),
("показать", "to show, display", 3),
("вспомнить", "to remember, recall", 3),
("система", "system", 3),
("четыре", "four", 3),
("квартира", "flat, apartment", 3),
("держать", "to hold, keep", 3),
("также", "also, as well, too", 3),
("любовь", "love", 3),
("солдат", "soldier", 3),
("откуда", "where… from", 3),
("чтоб", "that, in order that, (See #74, 3)", 3),
("называть", "to call, name, (See #597, 3)", 3),
("третий", "third", 3),
("хозяин", "master, boss, host", 3),
("вроде", "like, not unlike", 3),
("уходить", "to leave, go away", 3),
("подойти", "to approach, come up(See #798, 3)", 3),
("поднять", "to lift, raise", 3),
("особенно", "especially, particularly", 3),
("спрашивать", "to ask, inquire", 3),
("начальник", "chief, head, superior", 3),
("оба", "both", 3),
("бросить", "to throw", 3),
("школа", "school", 3),
("парень", "boy, fellow, guy", 3),
("кровь", "blood", 3),
("двадцать", "twenty", 3),
("солнце", "sun", 3),
("неделя", "week", 3),
("послать", "to send, dispatch", 3),
("находиться", "to be found, turn up", 3),
("ребята", "guys, children", 3),
("поставить", "to put, place, set", 3),
("встать", "to get up, rise, stand up", 3),
("например", "for example, for instance", 3),
("шаг", "step", 3),
("мужчина", "man, male", 3),
("равно", "alike, in like manner", 3),
("нос", "nose", 3),
("мало", "little, few, (See #630, 3)", 3),
("внимание", "attention", 3),
("капитан", "captain, master", 3),
("ухо", "ear", 3),
("туда", "there", 3),
("сюда", "here", 3),
("играть", "to play", 3),
("следовать", "to follow, come next", 3),
("рассказать", "to tell, narrate(See #403, 3)", 3),
("великий", "great", 3),
("действительно", "indeed, really", 3),
("слишком", "too, too much", 3),
("тяжёлый", "heavy", 3),
("спать", "to sleep", 3),
("оставить", "to leave, abandon", 3),
("войти", "to enter, come in", 3),
("длинный", "long", 3),
("чувство", "feeling", 3),
("молчать", "to keep silence", 3),
("рассказывать", "to tell, narrate, (See #392, 3)", 3),
("отвечать", "to answer, reply, (See #190, 3)", 3),
("становиться", "to stand; to become", 3),
("остановиться", "to stop", 3),
("берег", "bank, shore, coast", 3),
("семья", "family", 3),
("искать", "to search", 3),
("генерал", "general", 3),
("момент", "moment, instant", 3),
("десять", "ten", 3),
("начать", "to begin(See #309, 3)", 3),
("следующий", "next, following", 3),
("личный", "personal", 3),
("труд", "labour, work", 3),
("верить", "to believe; masterrussian, dot com", 3),
("группа", "group", 3),
("немного", "a little", 3),
("впрочем", "however, though", 3),
("видно", "evidently, obviously", 3),
("являться", "to appear", 3),
("муж", "husband", 3),
("разве", "really?, perhaps", 3),
("движение", "movement", 3),
("порядок", "order", 3),
("ответ", "answer, reply", 3),
("тихо", "quietly, softly, slowly", 3),
("знакомый", "familiar, acquainted", 3),
("газета", "newspaper", 3),
("помощь", "help", 3),
("сильный", "strong, powerful", 3),
("скорый", "quick, fast", 3),
("собака", "dog", 3),
("дерево", "tree", 3),
("снег", "snow", 3),
("сон", "dream", 3),
("смысл", "sense, meaning, purpose", 3),
("смочь", "to be able", 3),
("против", "against, opposite, contrary to", 3),
("бежать", "to run, hurry", 3),
("двор", "yard, court", 3),
("форма", "form, shape, uniform", 3),
("простой", "simple, easy, plain", 3),
("приехать", "to arrive, come", 3),
("иной", "different, other", 3),
("кричать", "to cry, shout(See #656, 3)", 3),
("возможность", "possibility, opportunity, chance", 3),
("общество", "society", 3),
("зеленый", "green", 3),
("грудь", "breast, chest", 3),
("угол", "corner, angle", 3),
("открыть", "to open", 3),
("происходить", "to happen, occur, take place", 3),
("ладно", "in harmony, well, all right", 3),
("черный", "black (as in 'she wears black', 3)(See #333, 3)", 3),
("век", "century, age", 3),
("карман", "pocket", 3),
("ехать", "to go, ride, drive, travel", 3),
("немец", "German", 3),
("наверное", "probably, most likely(See #972, 3)", 3),
("губа", "lip", 3),
("дядя", "uncle", 3),
("приходить", "to come, arrive(See #253, 3)", 3),
("часто", "often", 3),
("домой", "home(as in 'she came home', 3)", 3),
("огонь", "fire", 3),
("писатель", "writer", 3),
("армия", "army", 3),
("состояние", "state, condition; fortune", 3),
("зуб", "tooth", 3),
("очередь", "line, queue, turn", 3),
("кой", "which (old-fashioned, literary, 3); mostly found in set expressions: ни в ко́ем слу́чае, ни ко́им о́бразом, в кои ве́ки, на кой чёрт?", 3),
("подняться", "to rise, climb", 3),
("камень", "stone", 3),
("гость", "guest", 3),
("показаться", "to appear, come in sight", 3),
("ветер", "wind", 3),
("собираться", "to gather together, assemble; intend(See #981, 3)", 3),
("попасть", "to hit; to find oneself", 3),
("принять", "to take, admit, accept(See #643, 3)", 3),
("сначала", "at first, from the beginning", 3),
("либо", "or", 3),
("поехать", "to depart, set off", 3),
("услышать", "to hear", 3),
("уметь", "to be able, know, can", 3),
("случиться", "to happen", 3),
("странный", "strange", 3),
("единственный", "only, sole", 3),
("рота", "company (military, 3)", 3),
("закон", "law, act, statue", 3),
("короткий", "short", 3),
("море", "sea", 3),
("добрый", "kind", 3),
("темный", "dark", 3),
("гора", "mountain, hill", 3),
("врач", "physician, doctor", 3),
("край", "border, edge; land, country", 3),
("стараться", "to try, endeavour", 3),
("лучший", "better, best", 3),
("река", "river", 3),
("военный", "military", 3),
("мера", "measure, step", 3),
("страшный", "terrible, frightful", 3),
("вполне", "quite, fully", 3),
("звать", "to call", 3),
("произойти", "to happen, occur, take place", 3),
("вперед", "forward", 3),
("медленно", "slowly", 3),
("возле", "by, near, close by", 3),
("никак", "in now way, by no means", 3),
("заниматься", "to be occupied, engage", 3),
("действие", "action, effect", 3),
("довольно", "enough; rather", 3),
("вещь", "thing", 3),
("необходимый", "necessary", 3),
("ход", "move", 3),
("боль", "pain", 3),
("судьба", "fate, fortune, destiny", 3),
("причина", "cause, reason, motive", 3),
("положить", "to lay down, put down, place", 3),
("едва", "hardly, just, barely", 3),
("черта", "line, boundary; trait", 3),
("девочка", "girl, little girl(See #326, 3)", 3),
("лёгкий", "light, easy", 3),
("волос", "hair", 3),
("купить", "to buy, purchase", 3),
("номер", "number, size, room, issue", 3),
("основной", "main", 3),
("широкий", "wide", 3),
("умереть", "to die", 3),
("далеко", "far, far off", 3),
("плохо", "badly", 3),
("глава", "head, chief", 3),
("красивый", "beautiful; masterrussian, dot com", 3),
("серый", "grey; dull", 3),
("пить", "to drink", 3),
("командир", "commander, commanding officer", 3),
("обычно", "usually", 3),
("партия", "party", 3),
("проблема", "problem, issue", 3),
("страх", "fear", 3),
("проходить", "to pass, go;study(See #334, 3)", 3),
("ясно", "clear, clearly", 3),
("снять", "to take away, take off;photograph", 3),
("бумага", "paper", 3),
("герой", "hero", 3),
("пара", "pair, couple", 3),
("государство", "State", 3),
("деревня", "village, country", 3),
("речь", "speech", 3),
("начаться", "to begin", 3),
("средство", "means, remedy", 3),
("положение", "position, posture, condition, state", 3),
("связь", "tie, bond; connection, relation", 3),
("скоро", "quickly, fast, soon", 3),
("небольшой", "small, not great", 3),
("представлять", "to present, introduce, imagine(See #586, 3)", 3),
("завтра", "tomorrow", 3),
("объяснить", "to explain", 3),
("пустой", "empty, hollow; idle", 3),
("произнести", "to pronounce, say, utter", 3),
("человеческий", "human", 3),
("нравиться", "to please, like", 3),
("однажды", "once, one day", 3),
("мимо", "past, by", 3),
("иначе", "otherwise, differentlyl", 3),
("существовать", "to exist, to be", 3),
("класс", "class", 3),
("удаться", "turn out well, succeed, manage", 3),
("толстый", "thick, heavy, fat", 3),
("цель", "goal, object, target", 3),
("сквозь", "through", 3),
("прийтись", "to fit, fall; have to", 3),
("чистый", "clean, pure", 3),
("знать", "to know(See #51, 3)", 3),
("прежний", "former", 3),
("профессор", "professor", 3),
("господин", "gentleman, Mr.", 3),
("счастье", "happiness, luck", 3),
("худой", "thin, skinny; masterrussian.com", 3),
("дух", "spirit", 3),
("план", "plan", 3),
("чужой", "somebody else's;strange, foreign", 3),
("зал", "hall", 3),
("представить", "to presetn, produce, introduce(See #558, 3)", 3),
("особый", "special", 3),
("директор", "director, manager", 3),
("бывший", "former, ex-", 3),
("память", "memory", 3),
("близкий", "near, similar; intimate", 3),
("сей", "this", 3),
("результат", "result, outcome", 3),
("больной", "sick", 3),
("данный", "given, present", 3),
("кстати", "to the point, at the same time", 3),
("назвать", "to call, name(See #356, 3)", 3),
("след", "track, footprint", 3),
("улыбаться", "to smile(See #605, 3)", 3),
("бутылка", "bottle", 3),
("трудно", "with difficulty", 3),
("условие", "condition, term", 3),
("прежде", "before", 3),
("ум", "mind, brains, intellect", 3),
("улыбнуться", "to smile(See #599, 3)", 3),
("процесс", "process", 3),
("картина", "picture, painting", 3),
("вместо", "instead", 3),
("старший", "elder, senior", 3),
("легко", "easily, lightly", 3),
("центр", "center", 3),
("подобный", "similar, like", 3),
("возможно", "as… as possible(as in 'as soon as possible', 3)", 3),
("около", "by, near", 3),
("смеяться", "to laugh", 3),
("сто", "hundred", 3),
("будущее", "future", 3),
("хватать ", "to snatch, seize; be sufficient(See #636, 3)", 3),
("число", "number", 3),
("всякое", "any, every", 3),
("рубль", "ruble", 3),
("почувствовать", "to feel", 3),
("принести", "to bring; masterrussian", 3),
("вера", "faith, belief", 3),
("вовсе", "quiet; not … at all", 3),
("удар", "blow, stroke", 3),
("телефон", "telephone", 3),
("колено", "knee", 3),
("согласиться", "to agree, consent", 3),
("мало", "little, few, not enough(See #384, 3)", 3),
("коридор", "corridor, passage", 3),
("мужик", "muzhik, man", 3),
("правый", "right", 3),
("автор", "author", 3),
("холодный", "cold, cool", 3),
("хватить", "to snatch, seize, suffice(See #618, 3)", 3),
("многие", "many", 3),
("встреча", "meeting, reception", 3),
("кабинет", "study, room, office suite", 3),
("документ", "document", 3),
("самолет", "aircraft, aeroplane", 3),
("вниз", "down, downwards", 3),
("принимать", "to take, admit, accept (See #481, 3)", 3),
("игра", "game, play", 3),
("рассказ", "story", 3),
("хлеб", "bread", 3),
("развитие", "development", 3),
("убить", "to kill", 3),
("родной", "own, native, dear", 3),
("открытый", "open", 3),
("менее", "less", 3),
("предложить", "to offer, propose, suggest", 3),
("желтый", "yellow", 3),
("приходиться", "to fit, fall; have to", 3),
("выпить", "to drink", 3),
("крикнуть", "to cry, shout(See #447, 3)", 3),
("трубка", "tube, roll, pipe", 3),
("враг", "enemy", 3),
("показывать", "to show, display", 3),
("двое", "two", 3),
("доктор", "doctor", 3),
("ладонь", "palm", 3),
("вызвать", "to call, send(See #821, 3)", 3),
("спокойно", "quietly", 3),
("попросить", "to ask", 3),
("наука", "science", 3),
("лейтенант", "lieutenant", 3),
("служба", "service, work", 3),
("оказываться", "to turn out, find oneself(See #183, 3)", 3),
("привести", "to bring", 3),
("сорок", "forty", 3),
("счет", "bill, account", 3),
("возвращаться", "to return", 3),
("золотой", "golden", 3),
("местный", "local", 3),
("кухня", "kitchen", 3),
("крупный", "large, big, prominent", 3),
("решение", "decision, conclusion", 3),
("молодая", "bride (See #288, 3); young (as an adjective, 3)", 3),
("тридцать", "thirty", 3),
("роман", "novel, romance", 3),
("требовать", "to demand", 3),
("компания", "company", 3),
("частый", "frequent", 3),
("российский", "Russian", 3),
("рабочий", "working", 3),
("потерять", "to lose", 3),
("течение", "current", 3),
("синий", "dark blue", 3),
("столько", "so much, so many", 3),
("теплый", "warm", 3),
("метр", "meter, metre", 3),
("достать", "to reach; get, obtain", 3),
("железный", "ferreous, iron", 3),
("институт", "institute", 3),
("сообщить", "to report, let know", 3),
("интерес", "interes", 3),
("обычный", "usual, ordinary", 3),
("появляться", "to appear, show up(See #335, 3)", 3),
("упасть", "to fall", 3),
("остальной", "remaining, the rest of", 3),
("половина", "half", 3),
("московский", "Moscow", 3),
("шесть", "six", 3),
("получиться", "to come, arrive, turn out", 3),
("качество", "quality", 3),
("бой", "battle, fight, combat", 3),
("шея", "neck", 3),
("вон", "out", 3),
("идея", "idea", 3),
("видимо", "apparently, seemingly", 3),
("достаточно", "enough, sufficiently", 3),
("провести", "to accompany, set off; conduct; spend (See #973, 3)", 3),
("важный", "important", 3),
("трава", "grass", 3),
("дед", "grandfather, old man", 3),
("сознание", "consciousness", 3),
("родитель", "parent; masterrussian, dot, com", 3),
("простить", "to forgive", 3),
("бить", "to beat, hit", 3),
("чай", "tea", 3),
("поздний", "late", 3),
("кивнуть", "to nod", 3),
("род", "family, clan, generation", 3),
("исчезнуть", "to disappear", 3),
("тонкий", "thin", 3),
("немецкий", "German", 3),
("звук", "sound", 3),
("отдать", "to return, give back", 3),
("магазин", "shop, store", 3),
("президент", "president; director", 3),
("поэт", "poet", 3),
("спасибо", "gratitude, thanks", 3),
("болезнь", "illness, sickness, disease", 3),
("событие", "event", 3),
("помочь", "to help (See #857, 3)", 3),
("кожа", "skin", 3),
("лист", "leaf, sheet", 3),
("слать", "to send", 3),
("вспоминать", "to remember, recall", 3),
("прекрасный", "beautiful, fine", 3),
("слеза", "tear", 3),
("надежда", "hope", 3),
("молча", "silently, without a word", 3),
("сильно", "strongly", 3),
("верный", "correct; faithful; reliable", 3),
("литература", "literature", 3),
("оружие", "weapon", 3),
("готовый", "ready", 3),
("запах", "smell, odour, scent", 3),
("неожиданно", "unexpectedly, suddenly", 3),
("вчера", "yesterday", 3),
("вздохнуть", "to take breath, to sigh", 3),
("роль", "role", 3),
("рост", "growth, increase; height", 3),
("природа", "nature", 3),
("политический", "political", 3),
("точка", "dot, point", 3),
("звезда", "star", 3),
("петь", "to sing", 3),
("садиться", "to sit down", 3),
("фамилия", "surname", 3),
("характер", "character, disposition, temper", 3),
("пожалуйста", "please", 3),
("выше", "higher", 3),
("офицер", "officer", 3),
("толпа", "crowd", 3),
("перестать", "to stop, cease", 3),
("придтись", "to fit, fall; have to", 3),
("уровень", "level", 3),
("неизвестный", "unknown", 3),
("кресло", "armchair", 3),
("баба", "woman, wife, old woman, (See #911, 3)", 3),
("секунда", "a second", 3),
("пожаловать", "to grant, bestow", 3),
("банк", "bank", 3),
("опыт", "experience", 3),
("тихий", "quiet, low, scelent", 3),
("поскольку", "so far as, since", 3),
("сапог", "(high, 3) boot", 3),
("правило", "rule", 3),
("стекло", "glass", 3),
("получать", "to receive, get (See #239, 3)", 3),
("внутренний", "inside, internal", 3),
("дочь", "daughter", 3),
("называться", "to call oneself", 3),
("надеяться", "to hope", 3),
("член", "member, limb", 3),
("протянуть", "to stretch, extend", 3),
("государственный", "State", 3),
("десяток", "ten, dozens", 3),
("глубокий", "deep", 3),
("цветок", "flower", 3),
("ах", "ah!, oh!", 3),
("желание", "wish", 3),
("дождь", "rain", 3),
("впереди", "before, in front of", 3),
("подходить", "to come up, approach;to fit(See #361, 3)", 3),
("много", "many, much, a lot of(See #187, 3)", 3),
("лоб", "forehead", 3),
("улыбка", "smile", 3),
("борьба", "fight, struggle", 3),
("ворот", "collar", 3),
("ящик", "box, case", 3),
("этаж", "floor, storey", 3),
("служить", "to serve", 3),
("вновь", "again, once more", 3),
("голубой", "blue, sky-blue", 3),
("нечего", "there is nothing, there is no need", 3),
("революция", "revolution", 3),
("впервые", "for the first time", 3),
("сосед", "neighbour", 3),
("сестра", "sister", 3),
("долгий", "long", 3),
("чей", "whose", 3),
("поверить", "to believe", 3),
("ситуация", "situation", 3),
("взглянуть", "to look, give a glance", 3),
("слабый", "weak", 3),
("количество", "quantity", 3),
("вызывать (See #663, 3)", "to call, send", 3),
("уверенный", "confident, sure", 3),
("выход", "exit", 3),
("совет", "advice; masterrussian, dot com", 3),
("дурак", "fool, idiot", 3),
("любимый", "dear, loved", 3),
("союз", "union, alliance; conjunction", 3),
("лето", "summer", 3),
("ожидать", "to expect", 3),
("пришлый", "alien, strange", 3),
("висеть", "to hang", 3),
("граница", "border", 3),
("цвет", "colour, color", 3),
("серьезный", "serious", 3),
("создать", "to create, establish", 3),
("интересно", "interestingly", 3),
("свобода", "freedom", 3),
("зато", "but, but then", 3),
("стул", "chair", 3),
("уехать", "to leave, depart", 3),
("поезд", "train", 3),
("музыка", "music", 3),
("быстрый", "quick, fast", 3),
("тень", "shadow", 3),
("лошадь", "horse", 3),
("поле", "field", 3),
("выглядеть", "to look", 3),
("учиться", "to study, learn", 3),
("левый", "left", 3),
("разговаривать", "to talk, speak", 3),
("детский", "child's, children's", 3),
("тип", "type, model", 3),
("суд", "court, law-court", 3),
("связанный", "related, connected, tied-up", 3),
("горячий", "hot", 3),
("площадь", "square, area", 3),
("помогать", "to help, assist(See #736, 3)", 3),
("счастливый", "happy", 3),
("повернуться", "to turn", 3),
("позволить", "to allow, permit", 3),
("встретить", "to meet", 3),
("радость", "gladness, joy", 3),
("острый", "sharp; spicy", 3),
("возраст", "age", 3),
("орган", "organ, body", 3),
("карта", "map", 3),
("входить", "to enter, come in", 3),
("обнаружить", "to discover, find out", 3),
("король", "king", 3),
("слава", "glory, fame", 3),
("полковник", "colonel", 3),
("мелкий", "shallow, small", 3),
("бок", "side, flank", 3),
("цена", "price", 3),
("информация", "information", 3),
("мозг", "brain", 3),
("удовольствие", "pleasure", 3),
("воля", "will", 3),
("область", "oblast, province; field", 3),
("крыша", "roof", 3),
("нести", "to carry", 3),
("обратно", "back, backwards", 3),
("современный", "contemporary, modern, up-to-date", 3),
("дама", "lady, partner, queen", 3),
("семь", "seven", 3),
("веселый", "cheerful, merry", 3),
("прислать", "to send", 3),
("сад", "garden, yard", 3),
("правительство", "government", 3),
("милый", "nice, sweet, dear", 3),
("относиться", "to treat, regard, relate", 3),
("возникать", "to arise, appear(See #951, 3)", 3),
("мол", "he says, they say, etc.", 3),
("повторить", "to repeat", 3),
("название", "name, title", 3),
("средний", "average, middle", 3),
("пример", "example", 3),
("невозможно", "impossible", 3),
("зеркало", "mirror", 3),
("погибнуть", "to perish, be killed", 3),
("американский", "American", 3),
("дым", "smoke", 3),
("гореть", "to burn", 3),
("плакать", "to cry", 3),
("весьма", "very, highly, greatly", 3),
("факт", "fact", 3),
("двигаться", "to move", 3),
("рыба", "fish", 3),
("добавить", "to add", 3),
("удивиться", "to wonder, be surprised", 3),
("бабушка", "grandmother(See #773, 3)", 3),
("вино", "wine", 3),
("ибо", "for", 3),
("учитель", "teacher, instructor", 3),
("действовать", "to act", 3),
("осторожно", "carefully, cautiously", 3),
("круг", "circle; masterrussian, dot com", 3),
("папа", "dad, daddy(See #165, 3)", 3),
("правильно", "correctly, properly", 3),
("недавно", "recently, lately", 3),
("держаться", "to hold on, behave", 3),
("причем", "moreover, and what's more", 3),
("лететь", "to fly", 3),
("носить", "to wear", 3),
("повод", "occasion, reason; bridle", 3),
("лагерь", "camp", 3),
("птица", "bird", 3),
("корабль", "ship", 3),
("мнение", "opinion", 3),
("ночной", "night", 3),
("здоровый", "healthy", 3),
("зима", "winter", 3),
("сухой", "dry", 3),
("километр", "kilometre, kilometer", 3),
("кровать", "bed", 3),
("привыкнуть", "to get used to, to grow accustomed to", 3),
("прочее", "et cetera, other", 3),
("свободный", "free", 3),
("лестница", "staircase", 3),
("неужели", "really, surely", 3),
("обязательно", "without fail, be sure", 3),
("вверх", "up, upwards", 3),
("детство", "childhood", 3),
("остров", "island", 3),
("статья", "article", 3),
("позвонить", "to call, to telephone", 3),
("столь", "so", 3),
("мешать", "to interfere, prevent; mix", 3),
("водка", "vodka", 3),
("темнота", "darkness", 3),
("возникнуть", "to arise, spring up(See #892, 3)", 3),
("способный", "capable (of, 3)", 3),
("станция", "station", 3),
("желать", "to wish", 3),
("попробовать", "to try, test", 3),
("получаться", "to come out", 3),
("гражданин", "citizen", 3),
("странно", "strangely", 3),
("вскоре", "soon, shortly", 3),
("интересный", "interesting", 3),
("команда", "team; command", 3),
("заболевание", "disease, illness", 3),
("живот", "stomach, belly", 3),
("ставить", "to put, place, set", 3),
("ради", "for the sake of", 3),
("тишина", "silence, stillness", 3),
("понятно", "clearly, plainly", 3),
("фронт", "front", 3),
("щека", "cheek", 3),
("страшно", "terribly, awfully", 3),
("район", "area, region", 3),
("наверно", "probably(See #461, 3)", 3),
("проводить", "to lead, escort; accompany(See #713, 3)", 3),
("выражение", "expression", 3),
("слегка", "slightly", 3),
("мешок", "bag, sack", 3),
("обещать", "to promise", 3),
("дорогой", "on the way", 3),
("судить", "to judge, try", 3),
("большинство", "majority", 3),
("собраться", "to gather, collect(See #479, 3)", 3),
("управление", "operation, control", 3),
("колоть", "to prick", 3),
("мокрый", "wet", 3),
("приказ", "order", 3),
("прямой", "straight", 3),
("закричать", "to shout, cry out", 3),
("кончиться", "to end", 3),
("куст", "bush", 3),
("стрелять", "to shoot", 3),
("художник", "painter, artist", 3),
("знак", "sign", 3),
("завод", "factory", 3),
("кулак", "fist", 3),
("использовать", "to use, utilize, make use of", 3),
("стакан", "glass", 3),
("пахнуть", "to smell", 3),
("отсюда", "from here", 3),
("рот", "mouth", 3),
("пора", "it's time;at times, now and then(See #279, 3)", 3)
;
