INSERT INTO tests(id, name) VALUES (5, "latin vocabulary");

INSERT INTO test (original, translation, testid) VALUES
("et", "and", 5),
("sum esse fuī futūrum", "be, exist; fut. infin. often = fore, impf. subj. often = forem for essem", 5),
("quī quae quod", "who, which, what", 5),
("que", "and (postpositive enclitic, 5)", 5),
("in", "in, on (+ abl., 5); into, onto (+ acc, 5)", 5),
("nōn", "not", 5),
("hic haec hoc", "this, these", 5),
("ille illa illud", "that", 5),
("tū tuī tibi tē", "you (sing., 5)", 5),
("cum", "with (prep. + abl., 5); when, since, although (conjunction + subj., 5)", 5),
("ego meī mihi mē", "I, me", 5),
("quisquam quicquam/quidquam", "any (single, 5) person, anyone at all", 5),
("is ea id", "he, she, it", 5),
("ad", "to, up to, towards (+acc., 5)", 5),
("ut, utī", "as (+ indic., 5); so that, with the result that (+ subj., 5); (in questions, 5) in what manner, how; (exclam., 5) to what an extent! how!", 5),
("sī", "if", 5),
("sui sibi sē/sēsē", "him- her- itself, themselves", 5),
("omnis -e", "all, every, as a whole", 5),
("nec", "and not, nor; nec ... nec, neither ... nor; → neque", 5),
("sed", "but", 5),
("ā ab abs", "from, by (+abl., 5)", 5),
("ipse ipsa ipsum", "him- her- itself", 5),
("possum posse potuī", "be able", 5),
("aut", "or", 5),
("māgnus -a -um", "great", 5),
("ex, ē", "out of, from (+ abl., 5)", 5),
("suus -a -um", "his own, her own, its own", 5),
("dō dare dedī datum", "give", 5),
("quam", "how?; (after comparative, 5) than", 5),
("per", "through (+acc., 5)", 5),
("videō vidēre vīdī vīsum", "see", 5),
("faciō facere fēcī factum", "do, make", 5),
("dīcō dīcere dīxī dictum", "say; causam dīcere, plead a case; diem dīcere, appoint a day", 5),
("iam", "now; already", 5),
("atque", "and in addition, and also, and; (after comparatives, 5) than; simul atque, as soon as; → ac", 5),
("ac", "and in addition, and also, and; (after comparatives, 5) than; simul ac, as soon as; → atque", 5),
("alius -a -ud", "other, another; ālias: at another time", 5),
("rēs reī f.", "thing (rēs pūblica, commonwealth; rēs familiāris, family property, estate; rēs mīlitāris, art of war; rēs novae, revolution, 5)", 5),
("habeō habēre habuī habitum", "have, hold", 5),
("animus -ī m.", "spirit, mind", 5),
("meus -a -um", "my", 5),
("deus -ī m.; dea -ae f.", "god; goddess", 5),
("multus -a -um", "much, many; multō, by far", 5),
("tuus -a -um", "your", 5),
("ferō ferre tulī lātum", "bear, carry, endure", 5),
("dē", "down from, about, concerning (+ abl., 5)", 5),
("nē", "lest, that not", 5),
("manus -ūs f.", "hand; band of men", 5),
("nūllus -a -um", "not any, no one", 5),
("nunc", "now", 5),
("nōs nostrum/nostrī nōbīs nōs", "we", 5),
("noster nostra nostrum", "our", 5),
("ūnus -a -um", "one", 5),
("diēs diēī m./f.", "day", 5),
("nihil, nīl", "nothing; not at all", 5),
("tum or tunc", "then", 5),
("enim", "for, indeed", 5),
("tamen", "nevertheless, still", 5),
("īdem eadem idem", "the same", 5),
("rēx rēgis m.", "king", 5),
("nam or namque", "for, indeed, really", 5),
("locus -ī m.", "place; loca (n. pl., 5) region", 5),
("veniō venīre vēnī ventum", "come", 5),
("inter", "between, among; during (+ acc., 5)", 5),
("pars partis f.", "part", 5),
("volō velle voluī", "wish, be willing", 5),
("etiam", "also, even", 5),
("bonus -a -um", "good", 5),
("agō agere ēgī āctum", "drive, do, act", 5),
("terra -ae f.", "land", 5),
("pater patris m.", "father, ancestor", 5),
("neque", "and not, nor; neque ... neque, neither ... nor; → nec", 5),
("domus -ūs f.", "house, home", 5),
("at", "but, but yet", 5),
("corpus corporis n.", "body", 5),
("quoque", "also, too", 5),
("aliquis -quae -quod", "some, any; si quis, si quid: anyone who, anything that", 5),
("tōtus -a -um", "whole, entire", 5),
("sīc", "in this manner, thus; sīc ... ut: in the same way as", 5),
("hīc", "here; hinc: from here", 5),
("iste ista istud", "that, that of yours; adv. istīc or istūc: over there; istinc: from over there", 5),
("urbs urbis f.", "city", 5),
("petō petere petīvī petītum", "seek, aim at", 5),
("iubeō iubēre iussī iussum", "bid, order", 5),
("vir virī m.", "man", 5),
("bellum -ī n.", "war", 5),
("vīta -ae f.", "life", 5),
("homō hominis m.", "human being", 5),
("tempus -oris n.", "time", 5),
("magis", "more", 5),
("prīmus -a -um", "first", 5),
("ubi", "where, when", 5),
("hostis -is m./f.", "stranger, enemy", 5),
("an", "or (in questions, 5); utrum ... an: whether ... or", 5),
("mors mortis f.", "death", 5),
("tam", "so, so much", 5),
("eō īre iī/īvī itum", "go", 5),
("arma -ōrum n. pl.", "arms, weapons", 5),
("superus -a -um", "situated above, upper", 5),
("nisi, nī", "if not, unless", 5),
("vincō vincere vīcī victum", "conquer", 5),
("pōnō pōnere posuī positum", "put, place; put aside", 5),
("dum", "while (+ indic., 5); until (+ subj., 5); provided that (+ subj., 5)", 5),
("sine", "without (+ abl., 5)", 5),
("tantus -a -um", "so great, so much; (as pronoun, 5) such a quantity, so much; tantī, at such a price, of such worth", 5),
("teneō -ēre -uī tentum", "hold, keep", 5),
("causa -ae f.", "cause, reason; causā + preceding genitive, for the sake of", 5),
("sequor sequī secūtus sum", "follow", 5),
("crēdō crēdere crēdidī crēditum", "believe", 5),
("accipiō -cipere -cēpī -ceptum", "receive", 5),
("virtūs -ūtis f.", "valor, manliness, virtue", 5),
("ante", "before, in front of (adv. and prep. + acc., 5)", 5),
("quaerō -rere -sīvī -sītum", "seek, inquire", 5),
("mittō mittere mīsī missum", "send, let go", 5),
("vīs f.", "force; (acc., 5) vim, (abl., 5) vī; (pl., 5) vīrēs, strength", 5),
("amor -ōris m.", "love", 5),
("caelum -ī n.", "sky, heavens", 5),
("sub", "under, close to (+acc. or abl., 5)", 5),
("nox noctis f.", "night", 5),
("ita", "thus, so", 5),
("rēgnum -ī n.", "kingship, kingdom", 5),
("populus -ī m.", "people", 5),
("autem", "moreover, but, however", 5),
("caput capitis n.", "head", 5),
("mare -is n.", "sea", 5),
("quīdam quaedam quoddam", "a certain one, someone", 5),
("māter mātris f.", "mother", 5),
("prō", "for, on behalf of, in proportion to (+abl., 5)", 5),
("quisquis quidquid", "whoever, whichever", 5),
("vōs", "you (pl., 5); (gen., 5) vestrum/vestrī, (dat./abl., 5) vōbīs, (acc., 5) vōs", 5),
("capiō capere cēpī captum", "seize", 5),
("quia", "because", 5),
("dūcō dūcere dūxī ductum", "lead; uxōrem dūcere, marry", 5),
("ergō", "therefore", 5),
("nōmen -inis n.", "name", 5),
("quidem", "certainly, at least", 5),
("miser misera miserum", "wretched, pitiable", 5),
("fortūna -ae f.", "fortune", 5),
("novus -a -um", "new", 5),
("gravis -e", "heavy, serious", 5),
("vel", "or else, or; even; vel ... vel: either … or", 5),
("longus -a -um", "long, far", 5),
("parvus -a -um", "small", 5),
("relinquō -linquere -līquī -lictum", "abandon", 5),
("saepe", "often", 5),
("fīō fierī factus sum", "become, happen, be done", 5),
("ōs ōris n.", "mouth, face", 5),
("alter altera alterum", "other of two", 5),
("semper", "always, ever", 5),
("deinde/dein", "then, next", 5),
("ignis -is m.", "fire", 5),
("modo", "just, just now; modo ... modo: now ... now, at one moment ... at another, sometimes ... sometimes", 5),
("timeō -ēre -uī", "to fear, to dread", 5),
("scelus -eris n.", "crime, sin", 5),
("dēbeō dēbēre dēbuī dēbitum", "owe, be obliged", 5),
("vīvō vīvere vīxī vīctum", "live", 5),
("fātum -ī n.", "fate; death", 5),
("vocō -āre", "call", 5),
("altus -a -um", "high, lofty; deep", 5),
("parō -āre", "prepare, acquire; parātus -a -um, ready", 5),
("mīles -itis m.", "soldier", 5),
("medius -a -um", "middle, central", 5),
("inquam, inquis, inquit, inquiunt:", "say (used with direct speech, 5)", 5),
("post", "after (adv. and prep. +acc., 5)", 5),
("audiō -īre -īvī/-iī -ītum", "hear, listen to", 5),
("putō -āre", "think, suppose", 5),
("annus -ī m.", "year", 5),
("stō stāre stetī statum", "stand", 5),
("vōx vōcis f.", "voice, utterance", 5),
("genus generis n.", "origin, lineage, kind", 5),
("referō referre rettulī relātum", "bring back; report", 5),
("sciō -īre -īvī/-iī -ītum", "know", 5),
("mēns mentis f.", "mind", 5),
("reddō -dere -didī -ditum", "return, give back", 5),
("licet licēre licuit licitum est", "it is permitted (+ dat. + infin., 5)", 5),
("sōlus -a -um", "only, alone", 5),
("fugiō fugere fūgī fugitum", "flee, escape", 5),
("ūllus -a -um", "any, anyone", 5),
("nēmō", "no one (gen. nūllīus, dat. nūllī, abl. nūllō or nūllā → nūllus -a -um, 5)", 5),
("nātūra -ae f.", "nature", 5),
("mōs mōris m.", "custom, habit; (pl., 5) character", 5),
("beneficium -ī n.", "service, kindness", 5),
("pectus -oris n.", "chest, breast", 5),
("fidēs -eī f.", "trust, faith", 5),
("patior patī passus sum", "permit, endure", 5),
("cūra -ae f.", "care, concern", 5),
("īra irae f.", "wrath, anger", 5),
("verbum -ī n.", "word", 5),
("prope", "near, next; (comp., 5) propior, (superl., 5) proximus; (adv., 5) prope, nearly, almost", 5),
("parēns -ntis m./f.", "parent", 5),
("puer puerī m.", "boy; slave", 5),
("moveō -ēre mōvī mōtum", "move", 5),
("dolor -ōris m.", "pain, grief", 5),
("gēns gentis f.", "family, clan", 5),
("modus -ī m.", "measure, manner, kind", 5),
("via -ae f.", "way, street", 5),
("quisque quaeque quidque", "each one, everyone", 5),
("amīcus -a -um", "friendly; (as subst., 5) friend", 5),
("pēs pedis m.", "foot", 5),
("imperium -ī n.", "command, power", 5),
("labor -ōris m.", "toil, exertion", 5),
("ingēns ingentis", "huge, enormous", 5),
("tālis tāle", "such", 5),
("parum", "too little", 5),
("apud", "near, in the presence of (+acc., 5)", 5),
("oculus -ī m.", "eye", 5),
("unda -ae f.", "wave, flowing water, water", 5),
("itaque", "and so, therefore", 5),
("vultus -ūs m.", "look, expression, face", 5),
("cadō cadere cecidī cāsum", "fall, be killed", 5),
("nātus -ī m.", "son", 5),
("quis quid", "who? what? which?", 5),
("trahō trahere trāxī trāctum", "drag, draw", 5),
("sanguis -inis m.", "blood", 5),
("metus -ūs m.", "fear, dread", 5),
("tantum, tantummodo", "only", 5),
("cōnsilium -ī n.", "plan; council, group of advisors", 5),
("coniunx coniugis m./f.", "spouse, husband, wife", 5),
("amō -āre", "to love; amāns -ntis m./f.: lover", 5),
("levis -e", "light, trivial", 5),
("duo duae duo", "two", 5),
("ferus -a -um", "wild, fierce; fera -ae f.: wild animal", 5),
("poena -ae f.", "penalty, punishment", 5),
("castrum -ī n.", "fortress, (regularly plural, castra camp, 5)", 5),
("frāter frātris m.", "brother", 5),
("haud", "not", 5),
("malus -a -um", "bad, evil", 5),
("iaceō iacēre iacuī", "lie", 5),
("līber lībera līberum", "free; līberī (m. pl., 5): freeborn children", 5),
("iter itineris n.", "journey, route", 5),
("ferrum -ī n.", "iron, iron weapon or implement", 5),
("spēs speī f.", "hope", 5),
("puella -ae f.", "girl; girl-friend", 5),
("silva -ae f.", "forest, grove", 5),
("bene", "well", 5),
("fīnis -is m.", "end, boundary", 5),
("gerō gerere gessī gestum", "bear, manage; bellum gerere, wage war", 5),
("ne (enclitic, 5)", "interrogative particle attached to the emphatic word in a question", 5),
("dux ducis m./f.", "leader, general", 5),
("premō premere pressī pressum", "press, pursue, overwhelm", 5),
("dominus -ī m.; domina -ae f.", "household master, lord; mistress", 5),
("mōns montis m.", "mountain", 5),
("uterque utraque utrumque", "each of two", 5),
("saevus -a -um", "fierce, raging, wrathful", 5),
("lītus -oris n.", "shore", 5),
("soleō -ēre -uī -itum", "be accustomed", 5),
("mīlle (pl., 5) mīlia", "thousand", 5),
("equus -ī m.", "horse", 5),
("dūrus -a -um", "hard, tough, harsh", 5),
("cōgō cōgere coēgī coāctum", "drive together; compel", 5),
("numquam", "never", 5),
("prīmum", "at first, firstly", 5),
("morior morī mortuus sum", "die", 5),
("carmen -inis n.", "song", 5),
("tēlum -ī n.", "missile, weapon, spear", 5),
("ratiō -ōnis f.", "method, plan, reason", 5),
("umbra -ae f.", "shade, shadow", 5),
("ars artis f.", "skill", 5),
("tot", "so many", 5),
("dexter -tra -trum", "right; dextera -ae f.: right hand", 5),
("sīgnum -ī n.", "sign, standard, mark", 5),
("laetus -a -um", "glad, joyful", 5),
("quālis -e", "of what kind? what?", 5),
("lēx lēgis f.", "law", 5),
("perīculum -ī n.", "danger", 5),
("nāscor nāscī nātus sum", "be born", 5),
("exercitus -ūs m.", "army", 5),
("pereō -īre -iī -itum", "perish, be lost", 5),
("ventus -ī m.", "wind", 5),
("audeō audēre ausus sum", "dare, be eager", 5),
("contrā", "against, opposite (adv. and prep. +acc., 5)", 5),
("aqua -ae f.", "water", 5),
("rapiō rapere rapuī raptum", "seize, tear away", 5),
("simul", "at the same time", 5),
("trīstis -e", "sad, solemn, grim", 5),
("mūnus mūneris n.", "gift, offering; duty, obligation; (pl., 5) gladiatorial show", 5),
("iuvenis -is m.", "youth", 5),
("fāma -ae f.", "rumor, fame", 5),
("adsum adesse affuī", "be present", 5),
("vērō", "in fact, certainly, without doubt", 5),
("pār paris", "equal", 5),
("vester vestra vestrum", "your", 5),
("flūmen -inis n.", "stream, river", 5),
("quīcumque quaecumque quodcumque", "who-, whatever", 5),
("certus -a -um", "sure, fixed", 5),
("fortis -e", "brave", 5),
("placeō placēre placuī placitum", "please", 5),
("vertō vertere vertī versum", "turn", 5),
("servō -āre", "save, watch over", 5),
("honor -ōris m.", "honor, glory; office, post", 5),
("dīgnus -a -um", "worthy", 5),
("cūnctus -a -um", "entire all together", 5),
("tollō tollere sustulī sublātum", "raise up, destroy", 5),
("negō -āre", "deny, refuse", 5),
("vetus veteris", "old", 5),
("eques equitis m.", "horseman, knight", 5),
("trādō -dere -didī -ditum", "hand over, yield", 5),
("flamma -ae f.", "flame, fire", 5),
("lūx lūcis f.", "light of day", 5),
("unde", "from where", 5),
("redeō -īre -iī -itum", "go back, return", 5),
("sentiō sentīre sēnsī sēnsum", "perceive, feel, hear, see", 5),
("aurum -ī n.", "gold", 5),
("cēdō cēdere cessī cessum", "go, move; yield", 5),
("quō", "for which reason; to or in what place; to what end, for what purpose?", 5),
("saxum -ī n.", "rock, cliff, crag", 5),
("ve", "or (postpositive enclitic, 5)", 5),
("aetās -tātis f.", "age, time of life", 5),
("fēlīx -īcis", "lucky", 5),
("loquor loquī locūtus sum", "speak, talk", 5),
("quantus -a -um", "(interr., 5) how great? (rel., 5) of what size, amount, etc. (as subst., 5) what amount? (rel., 5) which amount; quantī, at what price? (rel., 5) at which price", 5),
("coepī coepisse coeptus", "begin", 5),
("igitur", "therefore", 5),
("iūs iūris n.", "right, justice, law", 5),
("mūtō -āre", "change", 5),
("inveniō -venīre -vēnī -ventum", "find; discover", 5),
("prīnceps -cipis", "first, chief; (as subst., 5) leader, person in charge", 5),
("ops opis f.", "assistance, resources", 5),
("recipiō -cipere -cēpī -ceptum", "take back, receive; sē recipere, betake oneself, go", 5),
("sōl sōlis m.", "sun", 5),
("cōnsul -ulis m.", "consul", 5),
("orbis -is m.", "circle; orbis terrārum: world", 5),
("turba -ae f.", "crowd, uproar", 5),
("ager agrī m.", "field", 5),
("solvō solvere solvī solūtum", "release, set sail", 5),
("vitium -ī n.", "flaw, fault, crime", 5),
("vulnus -eris n.", "wound", 5),
("inde", "from there, from then", 5),
("senātus -ūs m.", "senate", 5),
("ūtor ūtī ūsus sum", "use, consume, employ (+ abl., 5)", 5),
("cōpia -ae f.", "abundance; (pl., 5) troops", 5),
("opus operis n.", "work", 5),
("colō colere coluī cultum", "inhabit, cultivate", 5),
("vōtum -ī n.", "solemn promise, vow; hope", 5),
("iugum -ī n.", "yoke; ridge, chain of hills", 5),
("quā", "where, how", 5),
("tellus tellūris f.", "earth", 5),
("numerus -ī m.", "number, amount", 5),
("cōgnōscō -gnōscere -gnōvī -gnitum", "learn, understand", 5),
("victor -ōris m.", "conqueror", 5),
("satis, sat", "enough, sufficient, sufficiently", 5),
("patria -ae f.", "fatherland, country", 5),
("seu", "whether; seu ... seu: whether ... or → sīve", 5),
("cāsus -ūs m.", "a fall; chance, accident", 5),
("frangō frangere frēgī frāctum", "break, shatter", 5),
("cīvitās -ātis f.", "citizenship, state", 5),
("nōscō nōscere nōvī nōtum", "learn, know", 5),
("proelium -ī n.", "battle", 5),
("ēripiō -ripere -ripuī -reptum", "snatch away, rescue, save", 5),
("mundus -ī m.", "world, universe, heavens", 5),
("cursus -ūs m.", "course, advance", 5),
("vix", "scarcely", 5),
("nāvis -is f.", "ship", 5),
("lacrima -ae f.", "tear", 5),
("hūmānus -a -um", "human", 5),
("mollis -e", "soft, yielding, gentle", 5),
("maneō manēre mānsī mānsum", "remain", 5),
("āgmen -minis n.", "line of march", 5),
("sīdus -eris n.", "star, constellation", 5),
("glōria -ae f.", "glory, fame", 5),
("diū:", "for a long time", 5),
("sīve", "whether; sīve ... sīve: whether ... or → seu", 5),
("tamquam", "so as, just as", 5),
("fuga -ae f.", "flight, route", 5),
("tūtus -a -um", "safe, protected", 5),
("auris -is f.", "ear", 5),
("aliēnus -a -um", "foreign, strange", 5),
("hūc", "to this place", 5),
("taceō -ēre -uī -itum", "be silent; tacitus -a -um, silent", 5),
("legiō -ōnis f.", "legion", 5),
("ostendō ostendere ostendī ostentum", "show, hold out", 5),
("socius -a -um", "friendly, allied; socius -ī m.: partner, comrade", 5),
("prōsum prodesse profuī", "be of use, do good, help (+ dat., 5)", 5),
("āra -ae f.", "altar", 5),
("lūmen luminis n.", "light", 5),
("tegō tegere tēxī tēctum", "cover, conceal", 5),
("turpis -e", "ugly, unsightly; disgraceful", 5),
("voluptās -ātis f.", "pleasure, enjoyment", 5),
("adhūc", "thus far, to this point", 5),
("grātia -ae f.", "favor, influence, gratitude", 5),
("iniūria -ae f.:", "injustice, wrong, affront", 5),
("latus -eris n.", "side, flank", 5),
("dulcis -e", "sweet", 5),
("postquam", "after", 5),
("extrēmus -a -um", "farthest, situated at the end or tip, extreme", 5),
("tēctum -ī n.", "roof; building, house", 5),
("ingenium -ī n.", "disposition, ability, talent", 5),
("pāx pācis f.", "peace", 5),
("canō canere cecinī cantum", "sing", 5),
("iuvō iuvāre iūvī iūtum", "help, assist; please, delight", 5),
("campus -ī m.", "plain, field", 5),
("claudō claudere clausī clausum", "close, shut", 5),
("doceō -ēre -uī doctum", "teach", 5),
("excipiō -cipere -cēpī -ceptum", "take out", 5),
("clārus -a -um", "clear, distinguished", 5),
("illīc", "at that place, there; illinc: from that place", 5),
("procul", "at a distance", 5),
("sacer sacra sacrum", "holy, sacred", 5),
("mora -ae f.", "delay, hindrance", 5),
("longē", "far, far off", 5),
("super", "over (adv. and prep. +acc., 5)", 5),
("errō -āre", "go astray, wander", 5),
("sēdēs -is f.", "seat, abode, habitation", 5),
("cūr", "why?", 5),
("coma -ae f.", "hair, tresses", 5),
("aiō", "say, affirm, say yes; ut āiunt: as they say", 5),
("gaudeō gaudēre gāvīsus sum", "rejoice", 5),
("beātus -a -um", "happy, blessed, prosperous, fortunate", 5),
("perveniō -venīre -vēnī -ventum", "arrive, reach", 5),
("vērus -a -um", "true", 5),
("incipiō -cipere -cēpī -ceptum", "begin", 5),
("parcō parcere pepercī parsum", "spare, be sparing of (+ dat., 5)", 5),
("vestis -is f.", "garment, robe, clothing", 5),
("similis -e", "like, similar", 5),
("caedēs -is f.", "killing, slaughter", 5),
("ōrdō -īnis m.", "order, rank", 5),
("optō -āre", "choose, select", 5),
("virgō -inis f.", "maiden, virgin, girl", 5),
("legō legere lēgī lēctum", "gather, choose, read", 5),
("aura -ae f.", "breeze", 5),
("impetus -ūs m.", "attack", 5),
("fōrma -ae f.", "shape; beauty", 5),
("praestō -stāre -stitī -stitum", "excel, exhibit", 5),
("aequor aequoris n.", "level surface, sea, plain", 5),
("misceō miscēre miscuī mixtum", "mix", 5),
("spatium -ī n.", "space", 5),
("tandem", "finally", 5),
("īnferus -a -um", "low; īnferior: lower; īnfimus or īmus: lowest", 5),
("metuō metuere metuī", "to fear, to dread", 5),
("temptō -āre", "try, test", 5),
("trānseō -īre -iī -itum", "go across", 5),
("ultimus -a -um", "farthest, final, last, ultimate", 5),
("addō -dere -didī -ditum", "give to", 5),
("grātus -a -um", "pleasant; grateful", 5),
("laudō -āre", "praise", 5),
("nōndum", "not yet", 5),
("impōnō -ere -posuī -positum", "put in, put on, impose, levy upon", 5),
("somnus -ī m.", "sleep, slumber; (pl., 5) dreams", 5),
("aciēs -ēī f.", "edge; line of battle", 5),
("rūrsus", "back, again", 5),
("cupiō -ere -īvī -ītum", "desire", 5),
("exspectō -āre", "watch, wait, expect", 5),
("compōnō -pōnere posuī positum", "build, construct, arrange", 5),
("laus laudis f.", "praise, glory", 5),
("absum abesse āfuī", "be away, absent", 5),
("ūsus -ūs m.", "use, experience", 5),
("velut", "even as, just as", 5),
("comes comitis m./f.", "companion, comrade; attendant, follower", 5),
("ob", "against, on account of (+acc, 5)", 5),
("studium -ī n.", "eagerness, zeal", 5),
("facilis -e", "easy", 5),
("nūmen -inis n.", "divine will, deity", 5),
("sapiēns -ntis", "wise; (as subst., 5) wise man, sage, philosopher", 5),
("sūmō sūmere sūmpsī sūmptum", "take up", 5),
("nōbilis -e", "distinguished, noble; (as subst., 5) a nobleman or woman", 5),
("quīn", "(adv., 5) indeed, in fact; (conjunction, 5) so that ... not (+ subj., 5)", 5),
("fleō flēre flēvī flētum", "weep", 5),
("nōlō nōlle nōluī", "be unwilling", 5),
("plēnus -a -um", "full", 5),
("adversus (-um, 5)", "(adv. and prep., 5) facing, opposite, against, opposed (to, 5)", 5),
("nemus nemoris n.", "grove, forest", 5),
("cārus -a -um", "dear", 5),
("dēsum -esse -fuī", "be lacking", 5),
("lēgātus -ī m.", "lieutenant, envoy", 5),
("discō -ere didicī", "learn", 5),
("furor -ōris m.", "rage, fury", 5),
("amnis -is m.", "river, torrent", 5),
("arbor arboris f.", "tree", 5),
("mox", "soon", 5),
("eō", "(adv., 5) there, to that place", 5),
("cīvis -is m./f.", "citizen", 5),
("occupō -āre", "seize, occupy; anticipate, do a thing first (+ infin., 5)", 5),
("spectō -āre", "look at, consider", 5),
("tergum -ī n.", "back, rear; ā tergō: from the rear", 5),
("crīmen -inis n.", "verdict, accusation", 5),
("dōnum -ī n.", "gift, present", 5),
("nōtus -a -um", "well-known", 5),
("sinus -ūs m.", "fold of a garment; lap, bay, gulf", 5),
("faciēs -ēī f.", "form, appearance", 5),
("rumpō rumpere rūpī ruptum", "break, rupture", 5),
("membrum -ī n.", "limb, member of the body", 5),
("umquam", "ever", 5),
("aspiciō -ere -spēxī -spectum", "look to or at, behold", 5),
("prius or priusquam", "before", 5),
("templum -ī n.", "consecrated ground; temple", 5),
("āmittō -mittere -mīsī -missum", "let go, send away", 5),
("pōscō pōscere popōscī", "demand, claim; inquire into", 5),
("perdō -dere -didī -ditum", "destroy", 5),
("quamvīs", "however you like; although", 5),
("tener -era -erum", "tender", 5),
("currus -ūs m.", "chariot", 5),
("precor -ārī", "pray, invoke", 5),
("anima -ae f.", "breath, spirit", 5),
("contingō -tingere -tigī -tactum", "touch, be contiguous to", 5),
("lībertās -ātis f.", "freedom", 5),
("servus -ī m.", "slave", 5),
("soror -ōris f.", "sister", 5),
("fluctus -ūs m", "flood, billow, surf", 5),
("quīppe", "(adv., 5) indeed, surely", 5),
("exigō -igere -ēgī -āctum", "drive out; collect", 5),
("fēmina -ae f.", "woman", 5),
("nimius -a -um", "too much, excessive", 5),
("fallō fallere fefellī falsum", "deceive", 5),
("mīror mīrārī mīrātus sum", "wonder at, marvel at (+ acc., 5)", 5),
("classis -is f.", "class, division, fleet", 5),
("sedeō sedēre sēdī sessum", "sit", 5),
("singulī -ae -a", "one each", 5),
("mūrus -ī m.", "wall", 5),
("noceō nocēre nocuī", "harm", 5),
("quoniam", "since, seeing that", 5),
("fax facis f.", "torch", 5),
("intellegō -legere -lēxī -lēctum:", "understand", 5),
("iungō iungere iūnxī iūnctum", "join", 5),
("afferō afferre attulī allātum", "bring to", 5),
("cōgitō -āre", "think, reflect", 5),
("līmen līminis n.", "threshold", 5),
("pūblicus -a -um", "public, belonging to the state", 5),
("queror querī questus sum", "complain of, lament", 5),
("exemplum -ī n.", "example, sample, copy", 5),
("prex precis f.", "prayers, entreaties", 5),
("dubitō -āre", "hesitate, doubt", 5),
("odium -ī n.", "hatred", 5),
("fundō fundere fūdī fūsum", "pour, scatter", 5),
("fūnus fūneris n.", "funeral; death; dead body", 5),
("nesciō -scīre", "not know, be ignorant", 5),
("prior prius", "earlier, preceding", 5),
("ūsque", "up to; continuously", 5),
("dubius -a -um", "doubtful; (as subst., 5) a doubt; sine dubiō, without a doubt, certainly", 5),
("tendō tendere tetendī tentum", "stretch, extend, direct (one’s steps or course, 5)", 5),
("pecūnia -ae f.", "money", 5),
("quemadmodum", "in what manner, how", 5),
("spargō spargere sparsī sparsum", "scatter", 5),
("trēs tria", "three", 5),
("tangō tangere tetigī tāctum", "touch", 5),
("respondeō -spondēre -spondī -spōnsum", "answer", 5),
("timor -ōris m.", "fear", 5),
("properō -āre", "hasten, speed", 5),
("subeō -īre -iī -itum", "go under; endure", 5),
("valeō valēre valuī", "be strong, excel, be valid, prevail; valē: farewell!", 5),
("condō -dere -didī -ditum", "build, found; store up; hide, conceal", 5),
("nefās n. indecl.", "impiety, wickedness", 5),
("quondam", "formerly, once", 5),
("auxilium -ī n.", "support, assistance; (pl., 5) auxiliary forces", 5),
("dēserō -ere dēseruī dēsertum", "leave, desert, abandon", 5),
("nūdus -a -um", "naked, bare", 5),
("auctor -ōris m.", "originator, founder", 5),
("animal -ālis n.", "a living being, an animal", 5),
("decus decoris n.", "beauty, grace; ornament, glory, honor", 5),
("salūs -ūtis f.", "health, safety", 5),
("pateō patēre patuī", "lie open, extend; be evident or obvious", 5),
("rogō -āre", "ask", 5),
("uxor uxōris f.", "wife", 5),
("abeō -īre -iī -itum", "go away", 5),
("regō regere rēxī rēctum", "guide, rule", 5),
("adeō", "(adv., 5) to such a degree, so", 5),
("auferō auferre abstulī ablātum", "take away", 5),
("quantum", "(adv., 5) how much? how greatly? how much! how greatly! as much as", 5),
("senex -is m.", "old man, elder; senior, older", 5),
("frōns frontis f.", "forehead, brow; front", 5),
("propter", "because of (+ acc., 5)", 5),
("rēgius -a -um", "kingly, royal", 5),
("currō currere cucurrī cursum", "run", 5),
("pellō pellere pepulī pulsum", "strike, beat, push, drive", 5),
("dīves dīvitis", "rich (poet. dīs, dītis, 5)", 5),
("iūdicō -āre", "judge, decide", 5),
("pecus -oris n.", "cattle, sheep", 5),
("potēns potentis", "able, powerful", 5),
("scrībō scrībere scrīpsī scrīptum", "write", 5),
("pulcher -chra -chrum", "beautiful", 5),
("surgō surgere surrēxī surrēctum", "rise", 5),
("cēterum", "for the rest, in addition, however that may be", 5),
("careō -ēre -uī", "lack (+ abl., 5)", 5),
("efficiō -ficere -fēcī -fectum", "bring about, complete; render (+ ut + subj., 5)", 5),
("ōlim", "formerly, at that time", 5),
("sermō -ōnis m.", "conversation, discourse", 5),
("exerceō -ercēre -ercuī -ercitum", "train, exercise, carry on", 5),
("gradus -ūs m.", "step, pace; grade, rank", 5),
("agitō -āre", "drive", 5),
("fortē", "by chance", 5),
("honestus -a -um", "honorable", 5),
("moror morārī morātus sum", "delay", 5),
("praesidium -ī n.", "garrison, protection", 5),
("sonō sonāre sonuī sonitum", "sound, resound", 5),
("praebeō -ēre -uī -itum", "furnish, supply, render", 5),
("regiō -ōnis f.", "boundary, region", 5),
("sententia -ae f.", "opinion, judgment", 5),
("ācer ācris ācre", "sharp, piercing", 5),
("suprā", "above, beyond (adv. and prep. +acc., 5)", 5),
("brevis -e", "short, shallow, brief", 5),
("citus -a -um", "swift; citō swiftly", 5),
("cornu -ūs n.", "horn", 5),
("ingrātus -a -um:", "unpleasant, disagreeable", 5),
("moenia -ium n. pl.", "walls, fortifications", 5),
("vinculum -ī n.", "bond, fetter, tie", 5),
("adeō -īre -iī -itum", "go to", 5),
("cēterus -a -um", "the other, the others, the rest", 5),
("exeō -īre -iī -itum", "go forth", 5),
("mālō mālle māluī", "prefer", 5),
("speciēs -ēī f.", "aspect, appearance", 5),
("ultrā", "beyond, further (adv. and prep. + acc., 5)", 5),
("certē", "certainly, surely", 5),
("imperō -āre", "command, control", 5),
("male", "(adv., 5) badly", 5),
("prohibeō -ēre -uī -itum", "restrain, keep away", 5),
("clāmor -ōris m.", "outcry, shout", 5),
("dōnō -āre", "present with a gift (+ acc. of person and abl. of thing, 5)", 5),
("officium -ī n.", "service, duty", 5),
("committō -mittere -mīsī -missum", "join, entrust to (+ dat., 5); perform, do", 5),
("crēscō crēscere crēvī crētum", "grow, increase", 5),
("aequus -a -um", "equal", 5),
("factum -ī n.", "deed, accomplishment", 5),
("caedō caedere cecīdī caesum", "strike, kill, cut down", 5),
("exīstimō -āre", "think, believe", 5),
("accēdō -cēdere -cessī -cessum", "approach", 5),
("contemnō -temnere -tempsī -temptum", "despise, scorn, disdain", 5),
("pudor pudōris m.", "sense of shame, modesty, propriety", 5),
("antīquus -a -um", "ancient, old-time, former", 5),
("ārdeō ārdēre ārsī ārsum", "blaze, glow; be eager", 5),
("ibi", "there", 5),
("prōvincia -ae f.", "province; official duty", 5),
("quandō", "when?; since; sī quandō: if ever", 5),
("custōs custōdis m.", "guardian", 5),
("supersum -esse -fuī", "remain, survive; be superfluous (to, 5)", 5),
("dēsinō -sinere -siī -situm", "leave off, cease", 5),
("fessus -a -um", "weary, tired", 5),
("praeda -ae f.", "booty, prey", 5),
("memoria -ae f.", "recollection, memory", 5),
("dīvidō -ere dīvīsī dīvīsum", "divide, separate", 5),
("pretium -ī n.", "price, worth, reward; pretium operae: a reward for trouble", 5),
("pontus -ī m.", "the open sea, the deep", 5),
("varius -a -um", "changing, varied, various", 5),
("vehō vehere vēxī vectum", "carry; vehor vehī vectus sum: travel, ride", 5),
("falsus -a -um", "deceptive, false", 5),
("niger nigra nigrum", "black", 5),
("oppidum -ī n.", "town", 5),
("pondus ponderis n.", "weight", 5),
("arvum -ī n.", "ploughed land, field", 5),
("arx arcis f.", "citadel, castle; summit", 5),
("sors sortis f.", "lot, fate, destiny; oracle", 5),
("vīnum -ī n.", "vine, wine", 5),
("dīversus -a -um", "different, diverse", 5),
("orior orīrī ortus sum", "arise, begin", 5),
("ecce", "behold!", 5),
("quamquam", "however, although", 5),
("cōnferō cōnferre contulī collātum", "collect, bring to", 5),
("facinus facinoris n.", "deed, crime", 5),
("retineō -tinēre -tinuī -tentum", "hold back, keep", 5),
("spērō -āre", "to hope", 5),
("plēbs plēbis f.", "the common people", 5),
("pūgna -ae f.", "fist-fight; battle", 5),
("repetō -petere -petīvī -petītum", "demand, exact; revisit; call to mind, recollect; repeat", 5),
("cōnstituō -stituere -stituī -stitūtum", "establish, put together", 5),
("dēfendō -fendere -fendī -fēnsum", "defend, ward off", 5),
("marītus -ī m.", "husband", 5),
("cernō cernere crēvī crētum", "discern, separate", 5),
("superbus -a -um", "overbearing, proud, haughty", 5),
("adversus -a -um", "facing, opposed; unfavorable", 5),
("morbus -ī m.", "sickness, disease", 5),
("sānctus -a -um", "sacred, inviolable", 5),
("commūnis -e", "common, general", 5),
("dēdūcō -dūcere -dūxī -ductum", "launch, lead away", 5),
("rīpa -ae f.", "bank of a river", 5),
("concēdō -cēdere -cessī -cessum", "yield, withdraw", 5),
("hōra -ae f.", "hour", 5),
("vetō -āre vetuī vetītum", "forbid", 5),
("cohors cohortis f.", "cohort, band, troop", 5),
("gīgnō gīgnere genuī genitum", "beget, bear, bring forth", 5),
("superō -āre", "overcome, surpass, defeat", 5),
("maestus -a -um", "sad, sorrowful; depressing", 5),
("meminī meminisse", "remember, recollect", 5),
("impleō -ēre -plēvī -plētum", "fill in, fill up", 5),
("māgnitūdō -inis f.", "greatness, size", 5),
("vacuus -a -um", "empty", 5),
("vagus -a -um", "wandering, shifting", 5),
("vulgus -ī n. and m.", "the common people", 5),
("deficiō -ficere -fēcī -fectum", "fail, give out; revolt from", 5),
("occurrō -currere -cucurrī -cursum", "run to meet; come into one’s mind", 5),
("statuō -ere -uī -ūtum", "set up, determine", 5),
("ideō", "for this reason", 5),
("praemium -ī n.", "bounty, reward", 5),
("praetereā", "besides, moreover", 5),
("tertius -a -um", "third", 5),
("supplicium -ī n.", "punishment, penalty", 5),
("vātēs -is m.", "poet, bard", 5),
("astrum -ī n.", "star; constellation", 5),
("undique", "from all sides, on all sides", 5),
("canis -is m./f.", "dog", 5),
("ēdō ēdere ēdidī ēditum", "put forth, state, explain", 5),
("fateor fatērī fassus sum", "admit, confess; profess, declare; assent, say yes", 5),
("amīcitia -ae f.", "friendship", 5),
("aureus -a -um", "golden; splendid", 5),
("candidus -a -um", "white, fair", 5),
("interim", "meanwhile", 5),
("frūstrā", "in vain", 5),
("lateō latēre latuī", "lie hidden, be hidden", 5),
("os ossis n.", "bone", 5),
("sēcūrus -a -um", "free from care, tranquil; careless", 5),
("conveniō -venīre -vēnī -ventum", "assemble, meet; agree", 5),
("interficiō -ficere -fēcī -fectum", "kill", 5),
("appellō -pellāre", "call, address, name", 5),
("dolus -ī m.", "artifice, device, trick", 5),
("permittō -mittere -mīsī -missum", "yield, allow, permit", 5),
("spīritus -ūs m.", "breath, life, spirit", 5),
("intrā", "within (+ acc., 5)", 5),
("terreō terrēre terruī territum", "terrify, frighten", 5),
("fōns fontis m.", "spring, fountain", 5),
("invidia -ae f.", "envy, jealousy, hatred", 5),
("pugnō -āre", "fight", 5),
("augeō augēre auxī auctum", "increase", 5),
("littera -ae f.", "letter, (pl., 5) literature", 5),
("moneō monēre monuī monitum", "warn, advise", 5),
("dīvitiae -ārum f. pl.", "riches, wealth", 5),
("experior -perīrī -pertus sum", "try thoroughly, test, experience", 5),
("superī -ōrum m. pl.", "those above, i.e. the gods", 5),
("ōtium -ī n.", "leisure", 5),
("vestīgium -ī n.", "footstep, footprint, track", 5),
("sinō sinere sīvī situm", "allow, let go", 5),
("decet decēre decuīt", "it is right, proper, fitting (+ acc. + infin., 5)", 5),
("effundō -fundere -fūdī -fūsum", "pour out", 5),
("prōmittō -mittere -mīsī -missum", "send forth, offer", 5),
("fingō fingere fīnxī fīctum", "shape; invent", 5),
("respicio -ere -spēxī -spectum", "look back, regard, consider", 5),
("imperātor -ōris m.", "commander", 5),
("vacō vacāre", "be empty, open, unoccupied", 5),
("color -ōris m.", "color", 5),
("discēdō -ere -cessī -cessum", "go away, depart", 5),
("gaudium -ī n.", "delight, joy, pleasure", 5),
("caecus -a -um", "blind, unseeing; dark, obscure", 5),
("libet libēre libuit or libitum est", "it is pleasing (+ dat. + infin., 5)", 5),
("centum", "one hundred", 5),
("cōnstō -stāre -stitī", "agree; constat, it is established that (+ acc. and infin., 5)", 5),
("lingua -ae f.", "tongue; language", 5),
("multitūdō -inis f.", "multitude, number", 5),
("aeternus -a -um", "everlasting, eternal", 5),
("circā", "around (adv. and prep. +acc., 5)", 5),
("ōrātiō -ōnis f.", "speech, address", 5),
("potestās -ātis f.", "power", 5),
("tardus -a -um", "slow, sluggish, lingering", 5),
("for fārī fātus sum", "report, say", 5),
("humus -ī f.", "ground; humī: on the ground", 5),
("testis -is m.", "witness", 5),
("īnferō īnferre intulī illātum", "bring upon, against; bellum īnferre: make war on", 5),
("cūrō -āre", "watch over, look after, care for (+ acc., 5)", 5),
("aes aeris n.", "copper, bronze", 5),
("celer -is -e", "swift", 5),
("prōcēdō -cēdere -cessī -cessum", "go forth, advance", 5),
("mēnsa -ae f.", "table", 5),
("pius -a -um", "dutiful, devoted, just, pious", 5),
("iūdicium -ī n.", "judgment, decision, trial", 5),
("victōria -ae f.", "victory", 5),
("damnō -āre", "condemn", 5),
("rārus -a -um", "wide apart, loose, thin; rare, seldom", 5),
("tempestas -tātis f.", "period of time, season; bad weather, storm", 5),
("imāgō -inis f.", "image, form, figure", 5),
("ōrō -āre", "pray", 5),
("praeter", "by, along, past; besides, except (+ acc., 5)", 5),
("cōnsulō -sulere -suluī -sultum", "consult, plan (+ acc., 5); consider the interests of (+dat, 5)", 5),
("iterum", "again", 5),
("porta -ae f.", "gate", 5),
("intersum -esse -fuī", "to be between; take part in, attend (+dat., 5); interest, it is in the interest of (+ gen., 5)", 5),
("libīdō -inis f.", "passion, lust", 5),
("sustineō sustinēre sustinuī sustentum", "hold up, sustain", 5),
("aliquandō", "at some time, at length", 5),
("māiōrēs māiōrum m.", "ancestors", 5),
("reperiō -perīre -pperī -pertum", "find, find out", 5),
("intrō -āre", "enter", 5),
("pietās -tātis f.", "sense of duty, devotion, esp. between parents and children", 5),
("barbarus -ī m.", "foreigner, barbarian", 5),
("culpa -ae f.", "guilt, fault, blame", 5),
("iūstus -a -um", "right, just, fair", 5),
("dōnec", "until", 5),
("fluō fluere fluxī fluxum", "flow", 5),
("necesse (indecl. adj., 5)", "necessary", 5),
("reor rērī rātus sum", "think, imagine, suppose, deem", 5),
("tenebrae -brārum f. pl.", "darkness, the shadows", 5),
("saeculum -ī n.", "generation, age, century", 5),
("dīmittō -mittere -mīsī -missum", "send away", 5),
("licet", "even though", 5),
("cinis cineris m./f.", "ashes, embers", 5),
("cōnsistō -sistere -stitī", "take position; consist in, be composed of", 5),
("recēns -ntis", "fresh, new", 5),
("aliter", "otherwise, differently", 5),
("laedō laedere laesī laesum", "injure by striking, hurt", 5),
("probō -āre", "approve, prove; convince one (dat., 5) of a thing (acc., 5)", 5),
("doleō -ēre doluī", "feel pain or grief, grieve", 5),
("quārē", "how? why?", 5),
("antequam", "before", 5),
("reliquus -a -um", "remaining, rest", 5),
("semel", "once", 5),
("ōdī ōdisse", "hate", 5),
("sīcut", "just as", 5),
("peccō -āre", "commit a wrong, injure", 5),
("sēnsus -ūs m.", "feeling, emotion, sense", 5),
("exsilium -ī n.", "exile, banishment", 5),
("cor cordis n.", "heart; cordī est, it is pleasing to (+ dat., 5)", 5),
("dēnique", "finally", 5),
("sapientia -ae f.", "wisdom", 5),
("statim", "immediately", 5),
("accidō -cidere -cidī", "fall; happen", 5),
("dēcernō -cernere -crēvī -crētum", "determine, decide", 5),
("occīdō -cīdere -cīdī -cīsum", "kill, cut down", 5),
("dēscendō -scendere -scendī -scēnsum", "climb down, descend", 5),
("hiems hiemis f.", "winter", 5),
("contineō -tinēre -tinuī -tentum", "contain, restrain", 5),
("dēferō -ferre -tulī -lātum", "carry away, report", 5),
("oportet -ēre -uit", "it is proper, right (+ acc. + infin., 5)", 5),
("tribūnus -ī m.", "tribune, title of various Roman officials, as mīlitum, plēbis, aerāriī", 5),
("bōs bovis m.", "ox; gen. pl. boum", 5),
("īrāscor īrāscī īrātus sum", "grow angry; īrātus -a -um: angry", 5),
("aeger aegra aegrum", "sick", 5),
("forum -ī n.", "market-place, forum", 5),
("offerō offerre obtulī oblātum", "present, offer, expose", 5),
("revocō -āre", "call back, recall", 5),
("cingō cingere cīnxī cīnctum", "encircle, surround, gird", 5),
("integer -gra -grum:", "untouched, fresh, complete, whole", 5),
("validus -a -um", "strong", 5),
("alō alere aluī alitum", "nourish", 5),
("flōs flōris m.", "flower, bloom", 5),
("īctus -ūs m.", "blow, stroke", 5),
("colligō -ere -lēgī -lēctum", "gather together, collect", 5),
("pergō pergere perrēxī perrēctum", "continue, proceed; awaken", 5),
("praesēns -ntis", "present, in person, ready", 5),
("rēctus -a -um", "straight, direct", 5),
("lātus -a -um", "broad, wide", 5),
("praeceptum -ī n.", "rule, precept; command", 5),
("recēdō -cēdere -cessī -cessum", "step back, recoil, recede, withdraw", 5),
("utrum", "whether; utrum ... an: whether ... or", 5),
("famēs -is f.", "hunger, famine", 5),
("pariō parere peperī partum", "bring forth, give birth to; accomplish", 5),
("appāreō -ēre -uī", "appear, become visible", 5),
("quōmodo", "in what way, how?", 5),
("error -ōris m.", "wandering; error, mistake", 5),
("forsitan, fortasse", "perhaps, perchance", 5),
("convertō -vertere -vertī -versum", "turn about, turn, change", 5),
("proficīscor -ficīscī -fectus sum", "set forth, go", 5),
("secundus -a -um", "following; favorable; (as numeral, 5) second", 5),
("aperiō aperīre aperuī apertum", "open", 5),
("castus -a -um", "pure, spotless, chaste", 5),
("iūdex iūdicis m.", "judge, juror", 5),
("lapis lapidis m.", "stone", 5),
("nimis or nimium", "excessively", 5),
("onus oneris n.", "load, burden", 5),
("opera -ae f.", "labor, activity, work", 5),
("pauper -eris", "poor, lowly", 5),
("āēr āeris m.", "air", 5),
("negōtium -ī n.", "business", 5),
("pāreō pārēre pāruī", "obey", 5),
("subitō", "suddenly, unexpectedly", 5),
("argentum -ī n.", "silver, money", 5),
("ūtilis -e", "useful", 5),
("aethēr aetheris n.", "pure upper air, ether, heaven, sky", 5),
("mereō merēre meruī meritum", "deserve, merit; serve as a soldier", 5),
("portō -āre", "carry a load", 5),
("proprius -a -um", "one’s own, peculiar", 5),
("avis -is f.", "bird", 5),
("vanus -a -um", "empty; false, deceitful", 5),
("māteria -ae f.", "material, subject matter; timber, lumber", 5),
("paucī -ae -a", "few, a few", 5),
("voluntās -ātis f.", "wish, desire", 5),
("ēgregius -a -um", "distinguished, uncommon", 5),
("difficilis -e", "not easy, hard, difficult", 5),
("gladius -ī m.", "sword", 5),
("cibus -ī m.", "food", 5),
("certō -āre", "decide by contest; fight, compete, vie", 5),
("initium -ī n.:", "beginning", 5),
("pertineō -tinēre -tinuī", "extend over, reach; refer to, pertain to, be the business of", 5),
("quattuor", "four", 5),
("turbō -āre", "disturb, confuse", 5),
("cōnsūmō -sūmere -sūmpsī -sūmptum", "to use up, consume", 5),
("corrumpō -rumpere -rūpī -ruptum", "break up, destroy, ruin", 5),
("incidō incidere incidī", "fall upon, fall into; happen", 5),
("paulō, paulum", "to only a small extent, slightly, a little", 5),
("hospes hospitis m.", "guest, guest-friend; stranger; host", 5),
("rīdeō -ēre rīsī rīsum", "laugh, laugh at", 5),
("aevum -i n.", "eternity; lifetime, age", 5),
("audāx audācis", "bold, daring; reckless", 5),
("posterus -a -um", "next, later", 5),
("praetor -ōris m.", "praetor, one of the chief Roman magistrates", 5),
("rūs rūris n.", "country", 5),
("differō differre distulī dīlātum", "scatter; publish, divulge; differ; defer, postpone", 5),
("vītō -āre", "avoid, shun", 5),
("prīvātus -a -um", "personal, private", 5),
("serviō -īre", "be a slave, serve (+ dat., 5)", 5),
("vereor verērī veritus sum", "fear, stand in awe of", 5),
("ingredior -gredī -gressus sum:", "step in, enter", 5),
("addūcō -ere -dūxī -ductum", "lead to, induce", 5),
("hortor hortārī hortātus sum", "urge strongly, advise, exhort", 5),
("reus -ī m.", "defendant", 5),
("scīlicet", "certainly, of course", 5),
("comparō -āre", "get ready, provide; compare", 5),
("perpetuus -a -um", "unbroken, perpetual", 5),
("dēsīderō -āre", "long for, desire greatly", 5),
("celebrō -āre", "frequent, throng, crowd", 5),
("cōnficiō -ficere -fēcī -fectum", "complete, accomplish; destroy, kill, consume", 5),
("intendō -tendere -tendī -tentum:", "stretch out, strain", 5),
("iūrō -āre", "take an oath, swear; iūs iūrandum, oath", 5),
("sōlum", "only, merely", 5),
("auctōritās -ātis f.", "influence, clout, authority", 5),
("iaciō iacere iēcī iactum", "throw, hurl", 5),
("labōrō -āre", "toil, work; be in trouble or distress", 5),
("liber librī m.", "book", 5),
("lūna -ae f.", "moon", 5),
("prōtinus", "at once, forthwith", 5),
("aequē", "equally", 5),
("cōnor cōnārī cōnātus sum", "try, attempt", 5),
("cupīdō -inis f.", "desire, eagerness, craving", 5),
("ferē", "almost", 5),
("īnsula -ae f.:", "island", 5),
("fīlia -ae f.; fīlius -ī m.", "daughter; son", 5),
("narrō -āre", "relate, recount", 5),
("necessitās -tātis f.", "necessity, need", 5),
("ēgredior ēgredī ēgressus sum", "stride out, depart, disembark from (+ abl., 5)", 5),
("poēta -ae m.", "poet", 5),
("decem", "ten", 5),
("amplus -a -um", "large, spacious", 5),
("aptus -a -um", "fit, suitable", 5),
("cōnsequor -sequī -secūtus sum", "follow up, overtake, attain", 5),
("frequēns -ntis", "in large numbers, often", 5),
("nūntius -ī m.", "messenger; news", 5),
("condīciō -ōnis f.", "agreement, condition", 5),
("convīvium -iī n.", "banquet, feast", 5),
("foedus -a -um", "foul", 5),
("fruor fruī frūctus sum", "enjoy the produce of, profit by, use (+ abl., 5)", 5),
("num", "interrogative particle implying negative answer", 5),
("albus -a -um", "white", 5),
("damnum -ī n.", "damage, injury", 5),
("frūctus -ūs m.", "fruit, crops; enjoyment, delight", 5),
("cēnseō cēnsēre cēnsuī cēnsum", "assess, rate; think, decide", 5),
("prōdō prōdere prōdidī prōditum", "publish, hand down; give over, betray", 5),
("prōpōnō -pōnere -posuī -positum", "put forth, propose, present", 5),
("īnstituō -stituere -stituī -stitūtum:", "undertake; equip", 5),
("item", "likewise", 5),
("magister magistrī m.", "master, chief", 5),
("stella -ae f.", "star", 5),
("ēdūcō -dūcere -dūxī -ductum", "lead forth", 5),
("frūmentum -ī n.", "grain", 5),
("suscipiō -cipere -cēpī ceptum", "take up", 5),
("quasi", "as if", 5),
("sacerdōs -dōtis m./f.", "priest, priestess", 5),
("vīcīnus -a -um", "neighboring, near", 5),
("caveō cavēre cāvī cautum", "be on guard, beware", 5),
("ēligō ēligere ēlēgī ēlēctum", "pick out, select", 5),
("familia -ae f.", "household, family", 5),
("paene", "almost", 5),
("praecipiō -cipere -cēpī -ceptum", "anticipate, advise, warn", 5),
("sānus -a -um", "sound, sane", 5),
("potis -e", "powerful, able", 5),
("prīncipium -ī n.", "beginning", 5),
("sepulcrum -ī n.", "place of burial, tomb, grave", 5),
("mortālis -e", "liable to death, mortal; (as subst., 5) a mortal", 5),
("epistula -ae f.", "letter", 5),
("inimīcus -a -um:", "unfriendly; (as subst., 5) enemy", 5),
("interrogō -āre", "put a question to, ask (+ acc., 5)", 5),
("cōnsuētūdo -inis f.", "custom, habit", 5),
("illūc", "to that place", 5),
("dīgnitās -ātis f.", "worth, reputation, honor", 5),
("fugō -āre", "put to flight", 5),
("afficiō -ficere -fēcī -fectum", "affect, visit with (+ abl., 5)", 5),
("adhibeō -hibēre -hibuī -hibitum", "apply", 5),
("caelestis -e", "from or of heaven; caelestēs, the gods", 5),
("mulier -eris f.", "woman", 5),
("dīvus -a -um", "divine, godlike; (as subst., 5) a god", 5),
("arbitror arbitrārī arbitrātus sum", "consider, think", 5),
("posteā", "afterwards", 5),
("aedēs -is f.", "building; (pl., 5) house", 5),
("fābula -ae f.", "account, tale, story", 5),
("celeriter", "quickly", 5),
("plērus- plēra- plērumque", "the greater part, very many, most, the majority", 5),
("quiēscō quiēscere quiēvī quiētum", "keep quiet; sleep", 5),
("quotiēns", "interr. how many times? how often? rel. as often as, whenever", 5),
("scientia -ae f.", "knowledge", 5),
("cōnfiteor cōnfitērī cōnfessus sum", "admit (a fact, 5), confess (a crime, 5); reveal, disclose", 5),
("dīligō -ligere -lēxī -lēctum", "choose, cherish, love", 5),
("plērumque", "generally", 5),
("dormiō -īre", "sleep", 5),
("volucris -is f./m.", "bird", 5),
("volucer -cris -cre", "flying", 5),
("creō -āre", "produce, create; elect, choose", 5),
("fidēlis -e", "faithful", 5),
("indicō -āre", "point out, show, make known", 5),
("hodiē", "today", 5),
("disciplīna -ae f.", "training, instruction; learning, discipline", 5),
("vērē", "truly", 5),
("aegrē", "with difficulty", 5),
("advertō -vertere -vertī -versum", "turn towards", 5),
("adveniō -īre -vēnī -ventum", "come to, arrive at", 5),
("pendō pendere pependī pēnsum", "weigh, hang, suspend; pay", 5),
("studeō -ēre -uī", "be eager, be zealous, care for (+ dat., 5)", 5),
("ascendō -ere -scendī -scēnsum", "climb up, ascend", 5),
("vulgō", "commonly", 5),
("breviter", "briefly", 5),
("fors fortis f.", "chance", 5),
("fēlīciter", "luckily", 5),
("revertō -vertere -vertī", "turn back", 5),
("ēdīcō -dīcere -dīxī -dictum", "declare", 5),
("mundus -a -um", "clean, neat, elegant", 5)
;
