INSERT INTO tests(id, name) VALUES (6, "greek vocabulary");

-- next https://www.memrise.com/course/426582/top-4000-words-in-greek/51/?action=next

INSERT INTO test (original, translation, testid) VALUES
("ο", "the", 6),
("να", "[particle used to form the subjunctive and gerund]", 6),
("είμαι", "I am", 6),
("δεν", "not", 6),
("θα", "will, would", 6),
("και", "and", 6),
("μου", "me; my", 6),
("με", "with; by; me", 6),
("για", "for; about", 6),
("σου", "you (sg.); your (sg.)", 6),
("που", "that, which, who", 6),
("σε", "to; at; in; on; by; you (sg.)", 6),
("αυτός", "this, that; he (she, it)", 6),
("τι", "what", 6),
("του", "him, it; his, its", 6),
("ότι", "that", 6),
("από", "from; by; with", 6),
("της", "her", 6),
("όχι", "no", 6),
("ναι", "yes", 6),
("ένας", "a, an; one", 6),
("αν", "if, whether", 6),
("αλλά", "but", 6),
("εδώ", "here", 6),
("τους", "them; their", 6),
("σας", "you (pl.); your (pl.)", 6),
("μας", "us; our", 6),
("πρέπει", "must, have to, ought", 6),
("πολύ", "very", 6),
("γιατί", "why; because", 6),
("πως", "that", 6),
("τώρα", "now", 6),
("εγώ", "I", 6),
("εντάξει", "ok, alright", 6),
("κάτι", "something, anything", 6),
("ξέρω", "I know", 6),
("έχω", "I have", 6),
("μην", "not", 6),
("έτσι", "so, thus, like that", 6),
("εσύ", "you (sg.)", 6),
("καλά", "well; ok", 6),
("θέλω", "I want, desire", 6),
("όταν", "when", 6),
("μπορώ", "I can, am able; may", 6),
("κάνω", "I do", 6),
("μόνο", "only, just", 6),
("μαζί", "together; with", 6),
("εκεί", "there", 6),
("σαν", "like", 6),
("όλα", "everything", 6),
("τίποτα", "nothing, anything", 6),
("ευχαριστώ", "thank you", 6),
("πώς", "how", 6),
("ή", "or", 6),
("τόσο", "so, such", 6),
("ποτέ", "never, ever", 6),
("αυτοί", "these, those; they", 6),
("απλά", "simply; only, just", 6),
("έλα", "come; come on", 6),
("λοιπόν", "so; well", 6),
("υπάρχω", "I exist; there is, there are", 6),
("ακόμα", "still, yet", 6),
("μέσα", "in, into, inside, within; through", 6),
("το σπίτι", "the house, home", 6),
("τότε", "at that time, then", 6),
("πιο", "more", 6),
("ίσως", "maybe, perhaps", 6),
("πού", "where", 6),
("παρακαλώ", "please; you're welcome", 6),
("ο κύριος", "the gentleman, sir, Mr.", 6),
("νομίζω", "I think", 6),
("μετά", "after; with; afterwards, later; so", 6),
("πριν", "before; ago", 6),
("γεια", "hi, hey", 6),
("πάντα", "always", 6),
("λίγο", "a little, a bit", 6),
("πίσω", "behind, back", 6),
("όπως", "like, as", 6),
("η δουλειά", "the job, work", 6),
("η αλήθεια", "the truth; really, truly", 6),
("ποιος", "who, which", 6),
("λέω", "I say; tell", 6),
("δύο", "two", 6),
("όλοι", "everyone", 6),
("το παιδί", "the child", 6),
("ας", "let's; may, might", 6),
("άλλος", "other; more", 6),
("η ζωή", "the life", 6),
("βλέπω", "I see", 6),
("πάω", "I go", 6),
("έξω", "out, outside", 6),
("καλός", "good, nice", 6),
("επειδή", "because, because of", 6),
("κοιτάζω", "I look at", 6),
("μέχρι", "until", 6),
("πάνω", "on; above; up", 6),
("η ώρα", "the hour; time (quantity, time of day)", 6),
("η χρονιά", "the year", 6),
("η φορά", "the time (instance)", 6),
("ωραία", "nicely, beautifully; great!", 6),
("ούτε", "neither, nor", 6),
("κάποιος", "someone; some", 6),
("σωστά", "correctly; right?", 6),
("το πράγμα", "the thing", 6),
("κάθε", "every, each", 6),
("όμως", "however, but", 6),
("μα", "but", 6),
("κάτω", "under, below; down", 6),
("η μέρα", "the day", 6),
("η γυναίκα", "the woman; wife", 6),
("χωρίς", "without", 6),
("μόλις", "just, barely; as soon as", 6),
("η μαμά", "the mum", 6),
("ακριβώς", "exactly, precisely", 6),
("αρέσω", "I am liked (by somebody)", 6),
("σήμερα", "today", 6),
("πόσο", "how much; how many", 6),
("συγγνώμη", "sorry; excuse me", 6),
("ο θεός", "the god", 6),
("φαίνομαι", "I seem, appear", 6),
("λυπάμαι", "I am sorry, pity", 6),
("γίνομαι", "I become", 6),
("συμβαίνω", "I happen, occur", 6),
("το μέρος", "the part; place", 6),
("φυσικά", "naturally, of course", 6),
("πολύς", "much; many, a lot of", 6),
("όσο", "while, as long as", 6),
("η στιγμή", "the moment", 6),
("το λάθος", "the mistake", 6),
("ο χρόνος", "the time (concept); year", 6),
("οπότε", "so, therefore, thus", 6),
("περιμένω", "I wait for; expect", 6),
("το πρόβλημα", "the problem", 6),
("ως", "as; until, before (time); as far as (position)", 6),
("πάλι", "again", 6),
("πραγματικά", "really, truly", 6),
("όλος", "all; whole, entire", 6),
("χρειάζομαι", "I need", 6),
("ο φίλος", "the friend; boyfriend/girlfriend", 6),
("πιστεύω", "I believe", 6),
("δικός", "own", 6),
("η μητέρα", "the mother", 6),
("ίδιος", "same", 6),
("παίρνω", "I take; get", 6),
("γρήγορα", "quickly, fast", 6),
("η ιδέα", "the idea", 6),
("ο μπαμπάς", "the dad", 6),
("αρκετά", "enough; quite", 6),
("η κυρία", "the lady, madam, Mrs.", 6),
("σίγουρα", "certainly, sure", 6),
("τα λεφτά", "the money", 6),
("τα νέα", "the news", 6),
("νέος", "young; new", 6),
("εσείς", "you (pl.)", 6),
("μάλλον", "maybe, probably; rather, quite", 6),
("σημαίνω", "I mean, signify", 6),
("ήδη", "already, by now", 6),
("εμείς", "we", 6),
("ο πατέρας", "the father", 6),
("ο καιρός", "the weather; time", 6),
("προς", "towards, to", 6),
("εκτός", "except; out, outside", 6),
("το μωρό", "the baby", 6),
("ο κόσμος", "the world; people (public)", 6),
("η χαρά", "the joy, pleasure", 6),
("το όνομα", "the name", 6),
("αύριο", "tomorrow", 6),
("μόνος", "alone; single", 6),
("σταματάω", "I stop", 6),
("πρόκειται", "to be about to; it's about, it concerns", 6),
("η αγάπη", "the love", 6),
("μεγάλος", "big; great", 6),
("κανένας", "nobody", 6),
("ο άνθρωπος", "the person, human", 6),
("καταλαβαίνω", "Ι understand, realize", 6),
("πρώτος", "first", 6),
("το δίκιο", "the right", 6),
("απόψε", "tonight", 6),
("το τέλος", "the end", 6),
("τελευταίος", "last; latest, recent", 6),
("μακριά", "far, away", 6),
("αμέσως", "immediately; right away!", 6),
("πότε", "when", 6),
("η θέση", "the position, place", 6),
("ο τρόπος", "the way, manner", 6),
("μήπως", "by any chance", 6),
("εαυτός", "himself, herself, oneself, themselves", 6),
("ξανά", "again", 6),
("έρχομαι", "I come", 6),
("πια", "any more", 6),
("περισσότερος", "more", 6),
("κατά", "around, about; towards; during; against, versus", 6),
("μάλιστα", "yes, indeed", 6),
("το κορίτσι", "the girl", 6),
("η πόλη", "the city, town", 6),
("το λεπτό", "the minute", 6),
("ο τύπος", "the sort, type; the press; the formality; the guy", 6),
("κοντά", "near", 6),
("το θέμα", "the subject, matter", 6),
("μιλάω", "I speak, talk", 6),
("το χέρι", "the hand; arm", 6),
("βρίσκω", "I find", 6),
("τέτοιος", "such, like that", 6),
("εννοώ", "I mean (say sincerely; allude to)", 6),
("μερικοί", "some, certain", 6),
("πειράζω", "I tease, make fun of; bother", 6),
("εκείνος", "that, those", 6),
("η βοήθεια", "the help", 6),
("επίσης", "also; likewise", 6),
("καθόλου", "at all", 6),
("το όπλο", "the gun", 6),
("πέρα", "over, beyond", 6),
("σίγουρος", "safe, secure; sure, certain", 6),
("αφού", "since, as; after (having done something)", 6),
("η πόρτα", "the door", 6),
("η ιστορία", "the history; story; love affair", 6),
("ορίστε", "here you are, there you go; excuse me?", 6),
("ελπίζω", "I hope", 6),
("το πρωί", "the morning", 6),
("το μάτι", "the eye", 6),
("ο δρόμος", "the road; way; journey", 6),
("κακός", "bad", 6),
("η ομάδα", "the group; team", 6),
("η σχέση", "the relationship, connection", 6),
("μπροστά", "in front, ahead", 6),
("φεύγω", "I leave (somewhere)", 6),
("θυμάμαι", "I remember", 6),
("διάολε", "dammit!", 6),
("το αμάξι", "the car", 6),
("η αστυνομία", "the police", 6),
("η ευκαιρία", "the opportunity, chance", 6),
("ο λόγος", "the reason (cause); speech", 6),
("βοηθώ", "I help", 6),
("το κεφάλι", "the head", 6),
("η νύχτα", "the night", 6),
("ώστε", "so that, in order that", 6),
("χαίρομαι", "I am happy, glad; I enjoy", 6),
("γαμώτο", "fuck", 6),
("τέλεια", "perfectly; great!", 6),
("το γραφείο", "the office; desk", 6),
("το δωμάτιο", "the room", 6),
("δίνω", "I give", 6),
("η κόρη", "the daughter", 6),
("όπου", "where", 6),
("αγαπάω", "I love", 6),
("δηλαδή", "namely, that's to say", 6),
("πρώτα", "first; originally", 6),
("το ψέμα", "the lie", 6),
("τρία", "three", 6),
("ωραίος", "beautiful, handsome; nice", 6),
("ανησυχώ", "I worry", 6),
("η οικογένεια", "the family", 6),
("το αγόρι", "the boy", 6),
("πεθαίνω", "I die", 6),
("τα χρήματα", "the money", 6),
("ο άντρας", "the man; husband", 6),
("σοβαρά", "seriously", 6),
("αλλιώς", "otherwise", 6),
("μικρός", "small", 6),
("τουλάχιστον", "at least", 6),
("το τηλέφωνο", "the telephone", 6),
("δύσκολος", "difficult", 6),
("η καρδιά", "the heart", 6),
("αργότερα", "later", 6),
("σχεδόν", "almost, nearly", 6),
("το νερό", "the water", 6),
("νιώθω", "I feel", 6),
("κάπου", "somewhere", 6),
("πέντε", "five", 6),
("μεταξύ", "between, among", 6),
("ο μήνας", "the month", 6),
("χθες", "yesterday", 6),
("η υπόθεση", "the hypothesis, assumption; affair, matter; legal case", 6),
("αντίο", "goodbye", 6),
("το αίμα", "the blood", 6),
("το σχολείο", "the school", 6),
("βέβαια", "certainly, of course", 6),
("το μυαλό", "the mind", 6),
("ρε", "[Ιnformal interjection used to gain someone's attention, add emphasis or express surprise]", 6),
("σύντομα", "soon", 6),
("υποθέτω", "I suppose, guess", 6),
("πάρα", "too much", 6),
("σκατά", "shit!", 6),
("αργά", "slowly; late", 6),
("τρέχω", "I run", 6),
("συνέχεια", "continually, constantly", 6),
("η πλάκα", "the joke, fun; slab; plaque", 6),
("η φυλακή", "the prison", 6),
("σκέπτομαι", "I think, ponder", 6),
("το παιχνίδι", "the toy, game", 6),
("αφήνω", "I leave (something), let go of", 6),
("νεκρός", "dead", 6),
("γύρω", "around, about", 6),
("η σημασία", "the meaning; importance", 6),
("η χάρη", "the favour; grace", 6),
("η κοπέλα", "the girl; girlfriend", 6),
("το φαγητό", "the food; meal", 6),
("σημαντικός", "important, significant", 6),
("σκοτώνω", "I kill", 6),
("η κατάσταση", "the situation; state, condition", 6),
("συγχωρώ", "I forgive", 6),
("το αυτοκίνητο", "the car", 6),
("καλημέρα", "good morning, good day", 6),
("βασικά", "actually; basically", 6),
("το αστείο", "the joke", 6),
("εμπρός", "forward, ahead", 6),
("η Ελλάδα", "Greece", 6),
("φοβάμαι", "I am afraid, fear", 6),
("οι γονείς", "the parents", 6),
("γλυκός", "sweet", 6),
("έτοιμος", "ready", 6),
("το σχέδιο", "the plan; drawing; pattern", 6),
("νοιάζω", "I mind, care", 6),
("η τύχη", "the luck; fate", 6),
("το πόδι", "the foot, leg", 6),
("η αρχή", "the beginning; principle; authority", 6),
("μένω", "I stay; live (inhabit)", 6),
("ενώ", "while; although", 6),
("το ευρώ", "the euro", 6),
("ο Έλληνας", "the Greek person", 6),
("άσχημα", "badly, poorly", 6),
("τελικά", "finally, eventually", 6),
("οποίος", "who, which", 6),
("σωστός", "right, correct", 6),
("προσπαθώ", "I try", 6),
("ακούω", "I hear, listen", 6),
("μοιάζω", "I look like, resemble", 6),
("περίπου", "about, approximately", 6),
("η δύναμη", "the strength, force", 6),
("το ραντεβού", "the appointment; date", 6),
("το αφεντικό", "the boss, employer", 6),
("το πάρτι", "the party (social event)", 6),
("φέρνω", "I bring", 6),
("η γη", "the earth, land", 6),
("ακούγομαι", "I sound", 6),
("ο γιος", "the son", 6),
("η περίπτωση", "the occasion, instance", 6),
("επόμενος", "next, following", 6),
("το μισό", "the half", 6),
("το σώμα", "the body", 6),
("περνάω", "Ι pass, go past; cross", 6),
("ο διάλογος", "the conversation, discussion, dialogue", 6),
("το βιβλίο", "the book", 6),
("η επιλογή", "the choice", 6),
("μπράβο", "well done, bravo", 6),
("μαθαίνω", "I learn", 6),
("το νοσοκομείο", "the hospital", 6),
("προσέχω", "I watch, observe; look after; am careful", 6),
("έξι", "six", 6),
("η χώρα", "the country", 6),
("ο καφές", "the coffee", 6),
("το σεξ", "the sex, intercourse", 6),
("πλέον", "more; most; any more, any longer", 6),
("η ταινία", "the film, movie", 6),
("το μήνυμα", "the message", 6),
("εύκολος", "easy", 6),
("έι", "hey!", 6),
("σχετικά", "about, regarding; relatively", 6),
("αξίζω", "I am worth; deserve", 6),
("το πρόσωπο", "the face; character", 6),
("βρίσκομαι", "I am (placed, located); I am found; I meet (someone)", 6),
("το κρεβάτι", "the bed", 6),
("οτιδήποτε", "anything", 6),
("καληνύχτα", "good night", 6),
("ηρεμώ", "I calm down", 6),
("η ερώτηση", "the question (interrogative sentence)", 6),
("προφανώς", "obviously; apparently", 6),
("η συμφωνία", "the agreement, deal", 6),
("βάζω", "I put", 6),
("δίπλα", "next to", 6),
("το ποτό", "the drink", 6),
("η σειρά", "the row; series; turn (go)", 6),
("κάπως", "somehow, somewhat", 6),
("τελειώνω", "I finish", 6),
("παρά", "despite; rather than", 6),
("η πραγματικότητα", "the reality", 6),
("τα ρούχα", "the clothes", 6),
("δουλεύω", "I work", 6),
("το στοιχείο", "the element; evidence; data (in plural)", 6),
("τελευταία", "lately", 6),
("η λέξη", "the word", 6),
("ο γιατρός", "the doctor", 6),
("η αδερφή", "the sister", 6),
("υπέροχος", "wonderful, superb", 6),
("η φωτιά", "the fire", 6),
("παλιός", "old", 6),
("δέκα", "ten", 6),
("λίγος", "a little, a few", 6),
("το κομμάτι", "the piece; cut (of meat)", 6),
("το σημείο", "the point, spot, place", 6),
("γνωρίζω", "I know (someone); meet", 6),
("η πλευρά", "the side", 6),
("πουθενά", "nowhere", 6),
("υπέροχα", "wonderfully, superbly", 6),
("η εβδομάδα", "the week", 6),
("εντελώς", "completely", 6),
("περίεργος", "curious, inquisitive; weird", 6),
("η φωτογραφία", "the photo; photography", 6),
("η περιοχή", "the area, region; site", 6),
("τα ελληνικά", "Greek (language)", 6),
("η προσοχή", "the attention; be careful!", 6),
("το δείπνο", "the supper, dinner", 6),
("κάθομαι", "I sit", 6),
("η πληροφορία", "the information", 6),
("πόσος", "how much, how many", 6),
("το σκάφος", "the boat", 6),
("άρα", "therefore, consequently, so", 6),
("το μέλλον", "the future", 6),
("το ταξίδι", "the journey", 6),
("σκάσε", "shut up!", 6),
("η άδεια", "the permission; permit, license", 6),
("κάποτε", "once; one day, someday", 6),
("δείχνω", "I show, point to, indicate", 6),
("το άτομο", "the person, individual; atom", 6),
("καθώς", "as, while; since", 6),
("χάλια", "awful, terrible", 6),
("η μουσική", "the music", 6),
("ο θάνατος", "the death", 6),
("τα μαλλιά", "the hair", 6),
("η τιμή", "the price; honour", 6),
("είτε", "either, or", 6),
("τόσος", "so much, so many", 6),
("υποτίθεται", "it is supposed to, supposedly", 6),
("η γνώμη", "the opinion", 6),
("μακάρι", "if only; even if", 6),
("το σύστημα", "the system", 6),
("παντού", "everywhere", 6),
("ο πόλεμος", "the war", 6),
("το πτώμα", "the corpse", 6),
("η ασφάλεια", "the safety; insurance", 6),
("επιτέλους", "at last, finally", 6),
("υπό", "under (subject to; of lower rank)", 6),
("συνήθως", "usually", 6),
("το τμήμα", "the department, section; piece, portion", 6),
("ρωτάω", "I ask", 6),
("υπόσχομαι", "I promise", 6),
("η αποστολή", "the mission", 6),
("το κέντρο", "the centre", 6),
("ο γάμος", "the marriage, wedding", 6),
("η λίστα", "the list", 6),
("εναντίον", "against, versus", 6),
("το είδος", "the kind, species", 6),
("το φως", "the light", 6),
("ενδιαφέρων", "interesting", 6),
("η μέση", "the middle", 6),
("το δώρο", "the present, gift", 6),
("αλλάζω", "I change", 6),
("τρελός", "crazy", 6),
("συνεχίζω", "I continue, carry on", 6),
("όντως", "indeed, really", 6),
("όμορφος", "beautiful, handsome", 6),
("η έρευνα", "the research; investigation", 6),
("τέλειος", "perfect", 6),
("το νόημα", "the meaning", 6),
("η δεσποινίς", "the young lady; Miss", 6),
("το στόμα", "the mouth", 6),
("το μυστικό", "the secret", 6),
("λείπω", "I am absent, am missing", 6),
("ο έλεγχος", "the control", 6),
("η άκρη", "the edge, end, tip", 6),
("η ματιά", "the look, glance", 6),
("εν", "in, at", 6),
("το πλοίο", "the ship", 6),
("κρατάω", "I hold, keep", 6),
("πρώην", "former", 6),
("παραπάνω", "further up; above; extra", 6),
("λιγότερος", "less", 6),
("η επίθεση", "the attack", 6),
("άντε", "come on!; go on!", 6),
("η βάση", "the base; basis", 6),
("παίζω", "I play", 6),
("χάνω", "I lose", 6),
("βγαίνω", "I go out", 6),
("το ατύχημα", "the accident", 6),
("ο αέρας", "the air", 6),
("εξαιτίας", "because of, due to", 6),
("συχνά", "often", 6),
("βγάζω", "I take off, remove; pull; take out", 6),
("ένα εκατομμύριο", "one million", 6),
("το γλυκό", "the dessert, confection", 6),
("πέφτω", "I fall", 6),
("η ανάγκη", "the need", 6),
("τελείως", "completely", 6),
("ανάμεσα", "between, among", 6),
("το ξενοδοχείο", "the hotel", 6),
("ξαφνικά", "suddenly", 6),
("το παρελθόν", "the past", 6),
("ειλικρινά", "honestly", 6),
("αφορά", "it is about, concerns, relates to", 6),
("μισώ", "I hate", 6),
("λόγω", "because of, due to", 6),
("η γραμμή", "the line", 6),
("ο χώρος", "the space; venue", 6),
("αισθάνομαι", "I feel, sense", 6),
("η απάντηση", "the answer, reply", 6),
("ο αδερφός", "the brother", 6),
("ψηλά", "highly; overhead; high up", 6),
("η σκηνή", "the scene; tent", 6),
("νωρίς", "early; soon", 6),
("λέγομαι", "I am called", 6),
("ζωντανός", "alive; vivid", 6),
("η τηλεόραση", "the television", 6),
("παράξενος", "strange", 6),
("το τραπέζι", "the table", 6),
("το σήμα", "the signal, sign", 6),
("το τραγούδι", "the song", 6),
("χίλια", "one thousand", 6),
("ορκίζομαι", "I swear (promise)", 6),
("η γιαγιά", "the grandmother", 6),
("το μπαρ", "the bar, pub", 6),
("ζητάω", "I ask for, request", 6),
("το μπάνιο", "the bathroom", 6),
("τα συγχαρητήρια", "the congratulations", 6),
("τέσσερα", "four", 6),
("στέλνω", "I send", 6),
("η επαφή", "the contact", 6),
("ο ύπνος", "the sleep", 6),
("η φωνή", "the voice", 6),
("το κρίμα", "the shame, pity", 6),
("το κλειδί", "the key", 6),
("το πρόγραμμα", "the programme, schedule", 6),
("η μάχη", "the battle, fight", 6),
("σύμφωνα", "according to", 6),
("το μαγαζί", "the shop; bar", 6),
("αντί", "instead", 6),
("η κίνηση", "the movement, motion; traffic", 6),
("το αεροπλάνο", "the plane, airplane", 6),
("διαφορετικά", "otherwise; differently", 6),
("η απόφαση", "the decision, judgement", 6),
("αρκετός", "enough, adequate; several", 6),
("ανήκω", "I belong", 6),
("το δικαίωμα", "the right, entitlement", 6),
("δεξιά", "right (direction)", 6),
("το γεγονός", "the fact; event; incident", 6),
("η έκπληξη", "the surprise", 6),
("η μαλακία", "the masturbation; bollocks, bullshit", 6),
("κύριος", "main", 6),
("το νούμερο", "the number", 6),
("ο φόνος", "the murder", 6),
("η ψυχή", "the soul; psyche", 6),
("ειδικά", "particularly, especially", 6),
("η μηχανή", "the machine; engine", 6),
("το κινητό", "the mobile phone", 6),
("η συνάντηση", "the meeting, encounter", 6),
("ψάχνω", "Ι look for, search", 6),
("το μέτρο", "the metre; measure", 6),
("ο βασιλιάς", "the king", 6),
("η ησυχία", "the quiet, stillness, tranquility", 6),
("δεύτερος", "second", 6),
("επιστρέφω", "I return", 6),
("το προσωπικό", "the staff (personnel)", 6),
("ασφαλής", "safe", 6),
("δυνατά", "loudly; hard", 6),
("ανοίγω", "I open", 6),
("το κουτί", "the box", 6),
("ξεχνάω", "I forget", 6),
("το απόγευμα", "the afternoon", 6),
("σηκώνω", "I lift, raise", 6),
("η αναφορά", "the reference, mention; report", 6),
("το όνειρο", "the dream", 6),
("γυρίζω", "Ι turn; return, go back", 6),
("ο πρόεδρος", "the president; chairman", 6),
("καλησπέρα", "good evening", 6),
("εύκολα", "easily", 6),
("η απόδειξη", "the proof, evidence; receipt", 6),
("η τσάντα", "the bag, handbag", 6),
("το γράμμα", "the letter", 6),
("η βόλτα", "the stroll, walk; ride", 6),
("το ναρκωτικό", "the drug (illegal)", 6),
("τα Χριστούγεννα", "the Christmas", 6),
("πράγματι", "actually, indeed", 6),
("ο κανόνας", "the norm, convention; regulation", 6),
("μπαίνω", "I enter", 6),
("το πρωινό", "the breakfast", 6),
("χτυπάω", "I hit, strike", 6),
("το μάθημα", "the lesson; course", 6),
("φαντάζομαι", "I imagine", 6),
("ο κώλος", "the arse, ass", 6),
("ηλίθιος", "stupid", 6),
("η διαφορά", "the difference", 6),
("το διαμέρισμα", "the appartment", 6),
("σιγά", "slowly; quietly", 6),
("δυστυχώς", "unfortunately", 6),
("αληθινός", "true, real", 6),
("το παράθυρο", "the window", 6),
("το δικαστήριο", "the court (legal)", 6),
("πάντως", "in any case, anyway", 6),
("αναρωτιέμαι", "I wonder", 6),
("αλλού", "elsewhere", 6),
("η ελπίδα", "the hope", 6),
("απολύτως", "absolutely", 6),
("απλός", "simple, plain", 6),
("ο πλανήτης", "the planet", 6),
("ο αγώνας", "the match, game; struggle", 6),
("αρχίζω", "I start, begin", 6),
("η επιχείρηση", "the business, company", 6),
("χειρότερος", "worse", 6),
("λατρεύω", "I worship; adore, love", 6),
("η θεία", "the aunt", 6),
("απίστευτος", "incredible", 6),
("η τάξη", "the class; order, tidiness", 6),
("η εταιρεία", "the company, firm", 6),
("το κρασί", "the wine", 6),
("όποιος", "whoever, anyone, whichever", 6),
("το αρχείο", "the archive, file", 6),
("η ηλικία", "the age", 6),
("η θάλασσα", "the sea", 6),
("φτάνω", "I arrive", 6),
("η κάρτα", "the card", 6),
("η εκκλησία", "the church", 6),
("η Αμερική", "America", 6),
("η κόλαση", "the hell, inferno", 6),
("η πλάτη", "the back (anatomy)", 6),
("το στοίχημα", "the bet, wager", 6),
("το κάθαρμα", "the creep, bastard", 6),
("ενδιαφέρω", "I interest", 6),
("το παπούτσι", "the shoe", 6),
("αριστερά", "left (direction)", 6),
("το βίντεο", "the video", 6),
("αστείος", "funny, amusing", 6),
("η σκύλα", "the bitch", 6),
("το τσάι", "the tea", 6),
("ξαναβλέπω", "I see again, look again", 6),
("ο σκοπός", "the aim, purpose", 6),
("ο συγχρονισμός", "the timing; synchronisation", 6),
("ζω", "I live", 6),
("ο αρχηγός", "the leader, chief", 6),
("εξηγώ", "I explain", 6),
("η διόρθωση", "the correction", 6),
("δυνατός", "strong; possible", 6),
("συζητώ", "I discuss, debate", 6),
("μισός", "half", 6),
("μέσω", "through, via", 6),
("τυχερός", "lucky", 6),
("φτιάχνω", "I make; build", 6),
("ο λαιμός", "the neck, throat", 6),
("η κάμερα", "the video camera", 6),
("το χαρτί", "the paper (material/document)", 6),
("η σφαίρα", "the sphere; bullet", 6),
("το κτίριο", "the building", 6),
("καλώ", "I invite; call, summon", 6),
("όποτε", "whenever", 6),
("η υπηρεσία", "the service", 6),
("η εποχή", "the season; age, epoch", 6),
("πιθανόν", "possibly, probably", 6),
("η γλώσσα", "the language; tongue", 6),
("ο αριθμός", "the number", 6),
("σκληρά", "roughly, harshly", 6),
("ο χορός", "the dance", 6),
("τρώω", "I eat", 6),
("τηλεφωνώ", "I phone", 6),
("η τράπεζα", "the bank", 6),
("το φορτηγό", "the lorry, truck", 6),
("μπλε", "blue", 6),
("η συζήτηση", "the conversation, discussion, dialogue", 6),
("κόκκινος", "red", 6),
("ο πόνος", "the pain, ache", 6),
("προσωπικά", "personally", 6),
("το τέρας", "the monster, beast", 6),
("η βόμβα", "the bomb", 6),
("φοβερός", "terrible, dreadul; terrific, incredible", 6),
("εύχομαι", "I wish", 6),
("η διεύθυνση", "the address; direction; management", 6),
("η διάρκεια", "the duration, length", 6),
("η δόξα", "the glory, fame", 6),
("το σημάδι", "the mark, sign", 6),
("ευτυχώς", "fortunately, luckily", 6),
("η αλλαγή", "the change", 6),
("η μπύρα", "the beer", 6),
("η θεραπεία", "the treatment, cure; therapy", 6),
("η κυβέρνηση", "the government", 6),
("το δευτερόλεπτο", "the second (unit of time)", 6),
("πονάω", "I hurt, ache", 6),
("κοινός", "communal, shared; commonplace, unremarkable", 6),
("το κοινό", "the public; audience", 6),
("η μπάλα", "the ball", 6),
("ο στρατός", "the army, military", 6),
("το άλογο", "the horse", 6),
("βαθιά", "deeply", 6),
("η παρέα", "the group of friends", 6),
("το δάσος", "the wood, forest", 6),
("επικίνδυνος", "dangerous", 6),
("έγκυος", "pregnant", 6),
("το ζώο", "the animal", 6),
("το μαχαίρι", "the knife", 6),
("σοβαρός", "serious, grave", 6),
("γεμάτος", "full", 6),
("ο κίνδυνος", "the danger, risk", 6),
("η βασίλισσα", "the queen", 6),
("το διάστημα", "the period (of time); outer space", 6),
("η Αθήνα", "Athens", 6),
("το Παρίσι", "Paris", 6),
("ο δικηγόρος", "the lawyer", 6),
("πιάνω", "I catch", 6),
("η κουζίνα", "the kitchen", 6),
("χαλαρώνω", "I relax; loosen", 6),
("διαφορετικός", "different", 6),
("η εικόνα", "the picture, image; icon (religious)", 6),
("το ζευγάρι", "the pair, couple", 6),
("απαντάω", "I answer, reply", 6),
("οι διακοπές", "the holidays, vacation", 6),
("ειλικρινής", "honest, sincere", 6),
("ήρεμα", "calmy", 6),
("ο κόλπος", "the bay; vagina", 6),
("το κόλπο", "the trick, stunt", 6),
("η μύτη", "the nose", 6),
("το νησί", "the island", 6),
("η προσφορά", "the offer", 6),
("έξυπνος", "intelligent, clever", 6),
("καθένας", "everyone", 6),
("το κλαμπ", "the club, nightclub", 6),
("η αίθουσα", "the hall, auditorium; classroom", 6),
("εκτιμάω", "I appreciate, value", 6),
("το ίχνος", "the trace, trail", 6),
("μυστικά", "secretly", 6),
("το μέλος", "the member", 6),
("διότι", "because", 6),
("η λύση", "the solution", 6),
("κρύος", "cold", 6),
("επτά", "seven", 6),
("μαύρος", "black", 6),
("το ταξί", "the taxi", 6),
("το βήμα", "the pace, step", 6),
("η τουαλέτα", "the lavatory, toilet", 6),
("η αίσθηση", "the feeling, sensation, sense", 6),
("η πίστη", "the faith, belief", 6),
("ηλίθια", "stupidly, foolishly", 6),
("το έδαφος", "the ground; soil; territory", 6),
("άσχημος", "ugly, bad", 6),
("ταιριάζω", "I match, suit", 6),
("η ενέργεια", "the energy", 6),
("αρκώ", "I am enough", 6),
("η σκέψη", "the thought", 6),
("το έργο", "the work, project; film, play", 6),
("λειτουργώ", "I function, work, operate", 6),
("ο αστυνομικός", "the policeman", 6),
("τρίτος", "third", 6),
("η Τρίτη", "Tuesday", 6),
("κοιμάμαι", "I sleep", 6),
("ο μαλάκας", "the wanker, idiot", 6),
("ο σύζυγος", "the spouse (husband, wife)", 6),
("επί", "over (authority, control); by (multiplied by)", 6),
("η πίεση", "the pressure", 6),
("εξαρτώμαι", "I depend", 6),
("ο πελάτης", "the customer", 6),
("ο κυβερνήτης", "the governor, ruler", 6),
("ξεκινάω", "I start, begin", 6),
("ο λογαριασμός", "the bill (restaurant); account", 6),
("ελεύθερος", "free", 6),
("εξαφανίζομαι", "I disappear", 6),
("κιόλας", "already (so soon); as well", 6),
("ο στρατιώτης", "the soldier", 6),
("το έγκλημα", "the crime", 6),
("φταίω", "I am to blame, I am in the wrong", 6),
("το εργαστήριο", "the laboratory; workshop", 6),
("το τρένο", "the train", 6),
("συμφωνώ", "I agree", 6),
("η εμπιστοσύνη", "the trust, confidence", 6),
("η προσπάθεια", "the effort, attempt", 6),
("το παράδειγμα", "the example", 6),
("το Λονδίνο", "London", 6),
("φροντίζω", "I look after, take care of", 6),
("ο τοίχος", "the wall", 6),
("η τρύπα", "the hole", 6),
("ολόκληρος", "whole, entire", 6),
("αποκλείεται", "it's out of the question, no way", 6),
("ο σταθμός", "the station", 6),
("υπεύθυνος", "responsible, liable", 6),
("ο υπολογιστής", "the computer", 6),
("παθαίνω", "I come down with, sustain", 6),
("η πιθανότητα", "the probability, possibility", 6),
("η γέφυρα", "the bridge", 6),
("ευτυχισμένος", "happy", 6),
("ο παππούς", "the grandfather", 6),
("η στολή", "the uniform, costume", 6),
("κλείνω", "I close, shut; reserve, book", 6),
("η εμπειρία", "the experience", 6),
("το χωριό", "the village", 6),
("πραγματικός", "real, actual", 6),
("η πρόταση", "the suggestion, proposal; the sentence (grammatical)", 6),
("το καπέλο", "the hat", 6),
("το λεωφορείο", "the bus", 6),
("παραλίγο", "almost, nearly", 6),
("το γεύμα", "the meal; lunch", 6),
("το πνεύμα", "the spirit; wit", 6),
("ο σεβασμός", "the respect", 6),
("ο θείος", "the uncle", 6),
("προτιμάω", "I prefer", 6),
("η βραδιά", "the evening", 6),
("ο χρυσός", "the gold; golden", 6),
("η πρόσβαση", "the access", 6),
("δίκαιος", "fair, just", 6),
("υπόλοιπος", "remaining, rest of", 6),
("το βάρος", "the weight, burden", 6),
("η μετάφραση", "the translation", 6),
("η συμπεριφορά", "the behaviour; attitude", 6),
("η κλήση", "the call, summons; fine, ticket", 6),
("καινούργιος", "new", 6),
("η πτήση", "the flight", 6),
("το πάτωμα", "the floor", 6),
("το εστιατόριο", "the restaurant", 6),
("ρίχνω", "I throw; drop (intentionally); shoot", 6),
("η διαδικασία", "the process, procedure", 6),
("το επεισόδιο", "the episode", 6),
("το λουλούδι", "the flower", 6),
("ο στόχος", "the aim, target", 6),
("ξυπνάω", "I wake up", 6),
("άρρωστος", "ill, sick", 6),
("η εργασία", "the job, task", 6),
("το αποτέλεσμα", "the result, outcome; effect", 6),
("ο σκύλος", "the dog", 6),
("συνεχώς", "continually, constantly", 6),
("το δόντι", "the tooth", 6),
("το ρολόι", "the watch, clock", 6),
("η γωνία", "the corner; angle", 6),
("η μοίρα", "the fate, destiny", 6),
("ο έρωτας", "the love; sex", 6),
("η ειρήνη", "the peace", 6),
("η ζώνη", "the belt; zone", 6),
("ο Έλληνας", "the Greek person", 6),
("το χρώμα", "the colour", 6),
("το φόρεμα", "the dress", 6),
("οι ΗΠΑ", "the USA", 6),
("αγαπημένος", "favourite; dear, beloved", 6),
("το σκοτάδι", "the darkness, dark", 6),
("η συνέντευξη", "the interview", 6),
("το δέντρο", "the tree", 6),
("η ακρίβεια", "the accuracy, precision", 6),
("η πορεία", "the course, course of action; route; march, procession", 6),
("ήσυχος", "quiet, silent; calm", 6),
("η επιτυχία", "the success", 6),
("επίπεδος", "flat, even", 6),
("το επίπεδο", "the level", 6),
("η παράσταση", "the performance, show", 6),
("η λεπτομέρεια", "the detail", 6),
("ο ρόλος", "the role", 6),
("το μπουκάλι", "the bottle", 6),
("η κουβέντα", "the chat", 6),
("σκληρός", "hard, stiff; tough, harsh", 6),
("η εξέταση", "the exam, examination", 6),
("η προστασία", "the protection", 6),
("βόρεια", "north, northward", 6),
("επιπλέον", "moreover, besides; additionally", 6),
("ιδιαίτερα", "especially; significantly", 6),
("πληρώνω", "I pay", 6),
("το τηλεφώνημα", "the phone call", 6),
("κλέβω", "I steal", 6),
("καθαρά", "clearly, distinctly; purely", 6),
("εξάλλου", "besides, anyway", 6),
("η διαταγή", "the order, command", 6),
("κατευθείαν", "directly, straight away", 6),
("η ταχύτητα", "the speed; gear (automobile)", 6),
("το πουλί", "the bird", 6),
("η συμβουλή", "the advice", 6),
("κυρίως", "mainly, principally", 6),
("θαυμάσια", "wonderfully; great", 6),
("ο κόπος", "the hassle, effort, bother", 6),
("η καριέρα", "the career", 6),
("η εφημερίδα", "the newspaper", 6),
("η ευθύνη", "the responsibility, liability", 6),
("η ελευθερία", "the freedom", 6),
("οποιοσδήποτε", "whoever, whatever", 6),
("το δαχτυλίδι", "the ring (on finger)", 6),
("η πολιτική", "the politics; policy", 6),
("το συμβούλιο", "the board, council, committee", 6),
("η καταστροφή", "the disaster, catastrophe; destruction", 6),
("γράφω", "I write", 6),
("δύσκολα", "with difficulty", 6),
("η πηγή", "the source; spring (water)", 6),
("το φάντασμα", "the ghost", 6),
("η καρέκλα", "the chair", 6),
("γελοίος", "ridiculous, laughable", 6),
("η δολοφονία", "the murder, assassination", 6),
("η παραλία", "the beach", 6),
("λευκός", "white", 6),
("οκτώ", "eight", 6),
("η κρίση", "the crisis; judgment, estimation", 6),
("χαρούμενος", "cheerful, joyful, glad", 6),
("το πανεπιστήμιο", "the university", 6),
("σώζω", "I save, rescue", 6),
("καταφέρνω", "I manage to do [something], carry [something] off", 6),
("ωχ", "ouch!; oops!", 6),
("νότια", "south, southward", 6),
("το γάλα", "the milk", 6),
("πρόσφατα", "recently", 6),
("προχωράω", "Ι move forward, progress, proceed", 6),
("πιθανός", "probable, likely", 6),
("απέναντι", "opposite, facing", 6),
("τρομερός", "terrible; frightening; awesome, cool", 6),
("αδύνατος", "impossible; slim, slender", 6),
("το πάρκο", "the park", 6),
("τεράστια", "immensely", 6),
("η μνήμη", "the memory (mental recollection)", 6),
("η φύση", "the nature", 6),
("το σαββατοκύριακο", "the weekend", 6),
("κερδίζω", "I win; defeat; earn", 6),
("μυρίζω", "I smell", 6),
("ο επικεφαλής", "the head, person in charge", 6),
("όσος", "as much as, as many as; as long as; any", 6),
("το δέρμα", "the skin; leather", 6),
("το στήθος", "the chest; breasts", 6),
("η γάτα", "the cat", 6),
("ο διευθυντής", "the manager, director; headmaster", 6),
("το καλοκαίρι", "the summer", 6),
("η Παρασκευή", "Friday", 6),
("απαίσιος", "awful, terrible", 6),
("το κρέας", "the meat", 6),
("η πύλη", "the gate", 6),
("το πεδίο", "the field, scope", 6),
("καθαρός", "clean; pure", 6),
("τα σκουπίδια", "the rubbish, trash", 6),
("οδηγάω", "I drive; guide, lead", 6),
("η κούκλα", "the doll, puppet; stunner, beauty", 6),
("η μονάδα", "the unit", 6),
("πυροβολάω", "I shoot", 6),
("το φάρμακο", "the drug, medicine", 6),
("ο βοηθός", "the helper, assistant", 6),
("η φάση", "the phase", 6),
("απαίσια", "awfully, terribly", 6),
("η ζέστη", "the warmth, heat", 6),
("το παρόν", "the present, time being", 6),
("η θεωρία", "the theory", 6),
("ο ήρωας", "the hero", 6),
("το αεροδρόμιο", "the airport", 6),
("η αγορά", "the market; purchase", 6),
("η εκδίκηση", "the revenge", 6),
("εκατό", "one hundred", 6),
("η γεύση", "the taste", 6),
("ο γέρος", "the old man", 6),
("η αποθήκη", "the warehouse, storeroom", 6),
("προτείνω", "I suggest, propose", 6),
("σπουδαίος", "important", 6),
("η οδός", "the street", 6),
("προτού", "before", 6),
("κατάλληλος", "appropriate, suitable", 6),
("το υπόλοιπο", "the rest, remainder", 6),
("ο φιλαράκος", "the buddy, mate", 6),
("η διασκέδαση", "the fun, amusement", 6),
("η απειλή", "the threat", 6),
("έστω", "maybe so; at least", 6),
("ελέγχω", "I check, control", 6),
("τεράστιος", "huge, enormous", 6),
("η κηδεία", "the funeral", 6),
("η μαγεία", "the magic", 6),
("στραβά", "awry, amiss", 6),
("η γειτονιά", "the neighbourhood", 6),
("η πατρίδα", "the homeland, birthplace", 6),
("η έκρηξη", "the explosion, blast", 6),
("το θαύμα", "the miracle, wonder", 6),
("η εντολή", "the order, command", 6),
("το ξύλο", "the wood (material)", 6),
("ωστόσο", "however, nevertheless", 6),
("ο νόμος", "the law, rule", 6),
("δοκιμάζω", "I try, test; taste", 6),
("ο διάβολος", "the devil", 6),
("χρησιμοποιώ", "I use", 6),
("η ταυτότητα", "the identity", 6),
("άνετα", "comfortably", 6),
("ο ουρανός", "the sky", 6),
("νοιάζομαι", "I care", 6),
("συναντάω", "I meet", 6),
("τα μετρητά", "the cash", 6),
("περήφανος", "proud", 6),
("η νίκη", "the victory", 6),
("η στάση", "the stop; attitude; posture", 6),
("ισχύει", "it is valid; is in force; applies", 6),
("η σχολή", "the faculty", 6),
("η παγίδα", "the trap", 6),
("πετάω", "I fly; throw", 6),
("τα αγγλικά", "English (language)", 6),
("το ποτάμι", "the river", 6),
("το διάλειμμα", "the break, interval", 6),
("διάφορος", "various, several", 6),
("προσεκτικά", "carefully, cautiously", 6),
("η λογική", "the logic", 6),
("ο φόβος", "the fear", 6),
("το καθήκον", "the duty", 6),
("ο τόπος", "the location, spot", 6),
("τα γενέθλια", "the birthday", 6),
("ο Τούρκος", "the Turkish person", 6),
("το τέρμα", "the last stop, end point; maximum, upper limit", 6),
("παντρεύομαι", "I marry", 6),
("πλήρης", "complete; full", 6),
("αποφασίζω", "I decide", 6),
("περίεργα", "strangely, curiously", 6),
("επιτρέπω", "I allow", 6),
("καταπληκτικός", "amazing, astounding", 6),
("η λίμνη", "the lake", 6),
("άλλου", "elsewhere", 6),
("το φιλί", "the kiss", 6),
("τριγύρω", "around, all around; surrounding", 6),
("η κορυφή", "the top, peak", 6),
("ζεστός", "warm, hot; cosy, snug", 6),
("λαμβάνω", "I receive, get", 6),
("περί", "circa; about, concerning", 6),
("απασχολημένος", "busy, occupied", 6),
("δωρεάν", "free of charge", 6),
("το ποτήρι", "the glass, drinking glass", 6),
("ο βλάκας", "the moron, cretin", 6),
("η αξία", "the value, worth", 6)
;
